// SPECLANG-GENERATED
// This file is auto-generated by src/meta/generator.ts
// Source: @speclang/spec-generator

import * as fs from "fs-extra";
import * as path from "path";
import {
  SpecFile,
  SpecMetadata,
  Block,
  BlockKind,
  ProjectSpec,
  GenerateOptions,
  GenerateResult,
  UpdateResult,
  SpecChange,
} from "./types.js";

/**
 * SpecGenerator - Generate spec files from existing code
 * 
 * This is the core component for making SpecLang self-specifying.
 * It can analyze TypeScript, Go, Python, and other code files
 * and generate corresponding spec files.
 */
export class SpecGenerator {
  private projectRoot: string;
  private options: GenerateOptions;

  constructor(projectRoot: string = process.cwd(), options: GenerateOptions = {}) {
    this.projectRoot = projectRoot;
    this.options = {
      includeContent: true,
      parseBlocks: true,
      resolveReferences: true,
      targetLanguage: "typescript",
      ...options,
    };
  }

  /**
   * Generate a spec file from a TypeScript source file
   */
  async generateFromTypeScript(filepath: string): Promise<GenerateResult> {
    try {
      const fullPath = path.isAbsolute(filepath)
        ? filepath
        : path.join(this.projectRoot, filepath);

      if (!(await fs.pathExists(fullPath))) {
        return { success: false, errors: [`File not found: ${fullPath}`] };
      }

      const content = await fs.readFile(fullPath, "utf-8");
      const spec = this.typescriptToSpec(filepath, content);
      
      return { success: true, spec, errors: [] };
    } catch (error) {
      return { success: false, errors: [(error as Error).message] };
    }
  }

  /**
   * Generate a spec file from a Go source file
   */
  async generateFromGo(filepath: string): Promise<GenerateResult> {
    try {
      const fullPath = path.isAbsolute(filepath)
        ? filepath
        : path.join(this.projectRoot, filepath);

      if (!(await fs.pathExists(fullPath))) {
        return { success: false, errors: [`File not found: ${fullPath}`] };
      }

      const content = await fs.readFile(fullPath, "utf-8");
      const spec = this.goToSpec(filepath, content);
      
      return { success: true, spec, errors: [] };
    } catch (error) {
      return { success: false, errors: [(error as Error).message] };
    }
  }

  /**
   * Generate a spec file from a Python source file
   */
  async generateFromPython(filepath: string): Promise<GenerateResult> {
    try {
      const fullPath = path.isAbsolute(filepath)
        ? filepath
        : path.join(this.projectRoot, filepath);

      if (!(await fs.pathExists(fullPath))) {
        return { success: false, errors: [`File not found: ${fullPath}`] };
      }

      const content = await fs.readFile(fullPath, "utf-8");
      const spec = this.pythonToSpec(filepath, content);
      
      return { success: true, spec, errors: [] };
    } catch (error) {
      return { success: false, errors: [(error as Error).message] };
    }
  }

  /**
   * Generate project-level spec containing all specs
   */
  async generateProjectSpec(): Promise<ProjectSpec> {
    const specsDir = path.join(this.projectRoot, "specs");
    
    const northstar = await this.findNorthstar(specsDir);
    const core = await this.findSpecsByLayer(specsDir, 0);
    const components = await this.findSpecsByLayer(specsDir, 1, 5);
    const generated = await this.findGeneratedSpecs(specsDir);
    const implementation = await this.findImplementationSpecs(specsDir);

    return {
      northstar,
      core,
      components,
      generated,
      implementation,
    };
  }

  /**
   * Update an existing spec from code changes
   */
  async updateSpecFromCode(specPath: string, codePath: string): Promise<UpdateResult> {
    try {
      const fullSpecPath = path.isAbsolute(specPath)
        ? specPath
        : path.join(this.projectRoot, specPath);
      const fullCodePath = path.isAbsolute(codePath)
        ? codePath
        : path.join(this.projectRoot, codePath);

      if (!(await fs.pathExists(fullSpecPath))) {
        return { success: false, specPath, changes: [], errors: ["Spec file not found"] };
      }

      if (!(await fs.pathExists(fullCodePath))) {
        return { success: false, specPath, changes: [], errors: ["Code file not found"] };
      }

      const specContent = await fs.readFile(fullSpecPath, "utf-8");
      const codeContent = await fs.readFile(fullCodePath, "utf-8");
      
      const changes = this.detectChanges(specContent, codeContent, specPath, codePath);
      
      // Write updated spec if there are changes
      if (changes.length > 0) {
        const updatedSpec = this.applyChanges(specContent, changes);
        await fs.writeFile(fullSpecPath, updatedSpec, "utf-8");
      }

      return { success: true, specPath, changes, errors: [] };
    } catch (error) {
      return { success: false, specPath, changes: [], errors: [(error as Error).message] };
    }
  }

  /**
   * Generate specs for all source files in a directory
   */
  async generateFromDirectory(dirPath: string, specOutputDir: string): Promise<GenerateResult[]> {
    const results: GenerateResult[] = [];
    const fullDirPath = path.isAbsolute(dirPath)
      ? dirPath
      : path.join(this.projectRoot, dirPath);

    if (!(await fs.pathExists(fullDirPath))) {
      return [{ success: false, errors: [`Directory not found: ${fullDirPath}`] }];
    }

    const files = await this.getSourceFiles(fullDirPath);
    
    await fs.ensureDir(path.join(this.projectRoot, specOutputDir));

    for (const file of files) {
      const ext = path.extname(file);
      let result: GenerateResult;

      if (ext === ".ts" || ext === ".tsx") {
        result = await this.generateFromTypeScript(file);
      } else if (ext === ".go") {
        result = await this.generateFromGo(file);
      } else if (ext === ".py") {
        result = await this.generateFromPython(file);
      } else {
        continue;
      }

      if (result.success && result.spec) {
        const specPath = this.specPathForCode(file, specOutputDir);
        await fs.writeFile(specPath, result.spec.content, "utf-8");
        result.spec.filePath = specPath;
      }

      results.push(result);
    }

    return results;
  }

  // ===========================================================================
  // Private Methods
  // ===========================================================================

  private typescriptToSpec(filepath: string, content: string): SpecFile {
    const header = this.extractFileHeader(filepath, "typescript");
    const blocks = this.extractBlocksFromTypeScript(content);
    
    const specContent = this.renderSpecFile(header, blocks);
    
    return {
      header,
      blocks,
      content: specContent,
      filePath: filepath,
    };
  }

  private goToSpec(filepath: string, content: string): SpecFile {
    const header = this.extractFileHeader(filepath, "go");
    const blocks = this.extractBlocksFromGo(content);
    
    const specContent = this.renderSpecFile(header, blocks);
    
    return {
      header,
      blocks,
      content: specContent,
      filePath: filepath,
    };
  }

  private pythonToSpec(filepath: string, content: string): SpecFile {
    const header = this.extractFileHeader(filepath, "python");
    const blocks = this.extractBlocksFromPython(content);
    
    const specContent = this.renderSpecFile(header, blocks);
    
    return {
      header,
      blocks,
      content: specContent,
      filePath: filepath,
    };
  }

  private extractFileHeader(filepath: string, lang: string): SpecMetadata {
    const basename = path.basename(filepath, path.extname(filepath));
    const id = `@speclang/${basename.replace(/[-_]/g, "/")}`;
    
    return {
      id,
      version: "0.1.0",
      layer: 5,
      project_level: "Alpha",
      agent_support: "agent_autonomous",
      tags: [lang, "generated", "auto-generated"],
      short: `Auto-generated spec for ${path.basename(filepath)}`,
      status: "generated",
    };
  }

  private extractBlocksFromTypeScript(content: string): Block[] {
    const blocks: Block[] = [];
    const lines = content.split("\n");
    
    let currentBlock: Partial<Block> | null = null;
    let braceDepth = 0;
    let lineNumber = 0;

    // Class detection
    const classRegex = /^export\s+(class|interface|type|enum)\s+(\w+)/;
    // Function detection  
    const functionRegex = /^export\s+(async\s+)?function\s+(\w+)/;
    // Const detection
    const constRegex = /^export\s+(const|let|var)\s+(\w+)/;

    for (const line of lines) {
      lineNumber++;
      
      const classMatch = line.match(classRegex);
      const functionMatch = line.match(functionRegex);
      const constMatch = line.match(constRegex);

      if (classMatch || functionMatch || constMatch) {
        const match = classMatch || functionMatch || constMatch;
        const kind: BlockKind = classMatch ? "entity" : "code";
        
        blocks.push({
          id: `${match![2].toLowerCase()}`,
          kind,
          content: line.trim(),
          references: this.extractReferences(line),
          lineStart: lineNumber,
          lineEnd: lineNumber,
        });
      }

      // Track brace depth for blocks
      braceDepth += (line.match(/{/g) || []).length;
      braceDepth -= (line.match(/}/g) || []).length;
    }

    return blocks;
  }

  private extractBlocksFromGo(content: string): Block[] {
    const blocks: Block[] = [];
    const lines = content.split("\n");
    
    let lineNumber = 0;

    // Go type detection
    const typeRegex = /^(type|func|var|const)\s+(\w+)/;

    for (const line of lines) {
      lineNumber++;
      
      const match = line.match(typeRegex);
      if (match) {
        blocks.push({
          id: `${match[2].toLowerCase()}`,
          kind: match[1] === "type" ? "entity" : "code",
          content: line.trim(),
          references: this.extractReferences(line),
          lineStart: lineNumber,
          lineEnd: lineNumber,
        });
      }
    }

    return blocks;
  }

  private extractBlocksFromPython(content: string): Block[] {
    const blocks: Block[] = [];
    const lines = content.split("\n");
    
    let lineNumber = 0;
    let currentClass: string | null = null;

    // Python detection
    const classRegex = /^class\s+(\w+)/;
    const functionRegex = /^(\s*)def\s+(\w+)/;
    const constRegex = /^(\w+)\s*=\s*(?!.*def).*$/;

    for (const line of lines) {
      lineNumber++;
      
      const classMatch = line.match(classRegex);
      const functionMatch = line.match(functionRegex);

      if (classMatch) {
        currentClass = classMatch[1].toLowerCase();
        blocks.push({
          id: currentClass,
          kind: "entity",
          content: line.trim(),
          references: this.extractReferences(line),
          lineStart: lineNumber,
          lineEnd: lineNumber,
        });
      } else if (functionMatch && currentClass) {
        blocks.push({
          id: `${currentClass}/${functionMatch[2].toLowerCase()}`,
          kind: "code",
          content: line.trim(),
          references: this.extractReferences(line),
          lineStart: lineNumber,
          lineEnd: lineNumber,
        });
      }
    }

    return blocks;
  }

  private extractReferences(content: string): string[] {
    const refRegex = /@ref:([\w/.-]+)/g;
    const refs: string[] = [];
    let match;
    
    while ((match = refRegex.exec(content)) !== null) {
      refs.push(match[1]);
    }

    return refs;
  }

  private renderSpecFile(header: SpecMetadata, blocks: Block[]): string {
    const headerYaml = this.renderHeader(header);
    const blocksContent = blocks.map(b => this.renderBlock(b)).join("\n\n");
    
    return `# speclang-header lines:${headerYaml.split("\n").length + 2}
${headerYaml}
---

${blocksContent}
`;
  }

  private renderHeader(header: SpecMetadata): string {
    const lines = [
      `id: "${header.id}"`,
      `version: ${header.version}`,
      `layer: ${header.layer}`,
      `project_level: ${header.project_level}`,
      `agent_support: ${header.agent_support}`,
      `tags: [${header.tags.join(", ")}]`,
      `short: "${header.short}"`,
    ];
    
    if (header.status) {
      lines.push(`status: ${header.status}`);
    }
    
    return lines.join("\n");
  }

  private renderBlock(block: Block): string {
    const refs = block.references.length > 0 
      ? `\n\nrefs:\n${block.references.map(r => `  - @ref:${r}`).join("\n")}`
      : "";
    
    return `## @block:${block.id} @kind:${block.kind}
\`\`\`${block.kind === "code" ? "typescript" : "text"}
${block.content}
\`\`\`${refs}
`;
  }

  private async findNorthstar(dirPath: string): Promise<SpecFile | null> {
    const northstarPaths = [
      path.join(dirPath, "project.scl"),
      path.join(dirPath, "northstar.scl"),
    ];

    for (const p of northstarPaths) {
      if (await fs.pathExists(p)) {
        const content = await fs.readFile(p, "utf-8");
        return this.parseSpecFile(p, content);
      }
    }

    return null;
  }

  private async findSpecsByLayer(dirPath: string, min: number, max?: number): Promise<SpecFile[]> {
    const specs: SpecFile[] = [];
    
    const files = await fs.readdir(dirPath, { withFileTypes: true });
    
    for (const file of files) {
      if (file.isFile() && (file.name.endsWith(".spec.md") || file.name.endsWith(".scl"))) {
        const fullPath = path.join(dirPath, file.name);
        const content = await fs.readFile(fullPath, "utf-8");
        const spec = this.parseSpecFile(fullPath, content);
        
        if (max !== undefined) {
          if (spec.header.layer >= min && spec.header.layer <= max) {
            specs.push(spec);
          }
        } else if (spec.header.layer === min) {
          specs.push(spec);
        }
      }
    }

    return specs;
  }

  private async findGeneratedSpecs(dirPath: string): Promise<SpecFile[]> {
    const generatedDir = path.join(dirPath, "generated");
    
    if (!(await fs.pathExists(generatedDir))) {
      return [];
    }

    return this.findSpecsByLayer(generatedDir, 0);
  }

  private async findImplementationSpecs(dirPath: string): Promise<SpecFile[]> {
    const implDir = path.join(dirPath, "implementation.spec.dir");
    
    if (!(await fs.pathExists(implDir))) {
      return [];
    }

    const specs: SpecFile[] = [];
    const files = await fs.readdir(implDir, { withFileTypes: true });
    
    for (const file of files) {
      if (file.isFile() && file.name.endsWith(".spec.md")) {
        const fullPath = path.join(implDir, file.name);
        const content = await fs.readFile(fullPath, "utf-8");
        specs.push(this.parseSpecFile(fullPath, content));
      }
    }

    return specs;
  }

  private parseSpecFile(filepath: string, content: string): SpecFile {
    const header = this.parseHeader(content);
    const blocks = this.parseBlocks(content);
    
    return {
      header,
      blocks,
      content,
      filePath: filepath,
    };
  }

  private parseHeader(content: string): SpecMetadata {
    const headerMatch = content.match(/^# speclang-header lines:(\d+)\n([\s\S]*?)^---/m);
    
    if (!headerMatch) {
      return {
        id: "@unknown",
        version: "0.0.0",
        layer: 0,
        project_level: "POC",
        agent_support: "human_only",
        tags: [],
        short: "Unknown spec",
      };
    }

    const yamlContent = headerMatch[2];
    const lines: Record<string, string> = {};
    
    for (const line of yamlContent.split("\n")) {
      const colonIndex = line.indexOf(":");
      if (colonIndex > 0) {
        const key = line.slice(0, colonIndex).trim();
        const value = line.slice(colonIndex + 1).trim().replace(/^["']|["']$/g, "");
        lines[key] = value;
      }
    }

    return {
      id: lines["id"] || "@unknown",
      version: lines["version"] || "0.0.0",
      layer: parseInt(lines["layer"] || "0", 10),
      project_level: (lines["project_level"] as any) || "POC",
      agent_support: (lines["agent_support"] as any) || "human_only",
      tags: lines["tags"] ? lines["tags"].replace(/[\[\]]/g, "").split(",").map(t => t.trim()) : [],
      short: lines["short"] || "",
      status: lines["status"],
    };
  }

  private parseBlocks(content: string): Block[] {
    const blocks: Block[] = [];
    const blockRegex = /## @block:(\S+)\s+@kind:(\S+)\n([\s\S]*?)(?=\n## @block:|$)/g;
    
    let match;
    while ((match = blockRegex.exec(content)) !== null) {
      blocks.push({
        id: match[1],
        kind: match[2] as BlockKind,
        content: match[3].trim(),
        references: this.extractReferences(match[3]),
        lineStart: 0,
        lineEnd: 0,
      });
    }

    return blocks;
  }

  private detectChanges(specContent: string, codeContent: string, specPath: string, codePath: string): SpecChange[] {
    const changes: SpecChange[] = [];
    
    // Simple change detection: compare imports and exports
    const specImports = specContent.match(/@ref:[\w/.-]+/g) || [];
    const codeImports = codeContent.match(/import\s+.*from\s+['"](.*)['"]/g) || [];
    
    // Check for new exports in code that aren't in spec
    const codeExports = codeContent.match(/export\s+(class|function|const|interface|type)\s+(\w+)/g) || [];
    
    for (const exp of codeExports) {
      const name = exp.replace(/export\s+(class|function|const|interface|type)\s+/, "");
      if (!specContent.includes(name)) {
        changes.push({
          type: "added",
          blockId: name.toLowerCase(),
          description: `New export found in code: ${name}`,
        });
      }
    }

    return changes;
  }

  private applyChanges(specContent: string, changes: SpecChange[]): string {
    // For now, just append new blocks
    let result = specContent;
    
    for (const change of changes) {
      if (change.type === "added") {
        const newBlock = `\n## @block:${change.blockId} @kind:code\n\`\`\`typescript\n// Auto-generated from code\n\`\`\`\n`;
        result += newBlock;
      }
    }

    return result;
  }

  private async getSourceFiles(dirPath: string): Promise<string[]> {
    const files: string[] = [];
    const entries = await fs.readdir(dirPath, { withFileTypes: true });
    
    for (const entry of entries) {
      const fullPath = path.join(dirPath, entry.name);
      
      if (entry.isDirectory()) {
        const subFiles = await this.getSourceFiles(fullPath);
        files.push(...subFiles);
      } else if (/\.(ts|tsx|go|py)$/.test(entry.name)) {
        files.push(fullPath);
      }
    }

    return files;
  }

  private specPathForCode(codePath: string, outputDir: string): string {
    // If codePath is already absolute and outputDir is absolute, use direct path
    if (path.isAbsolute(codePath) && path.isAbsolute(outputDir)) {
      const relativePath = path.relative(path.dirname(outputDir), codePath);
      const basename = path.basename(relativePath, path.extname(relativePath));
      return path.join(outputDir, `${basename}.spec.md`);
    }
    
    const relativePath = path.relative(this.projectRoot, codePath);
    const basename = path.basename(relativePath, path.extname(relativePath));
    const dirName = path.dirname(relativePath);
    
    return path.join(this.projectRoot, outputDir, dirName, `${basename}.spec.md`);
  }
}

export default SpecGenerator;
