"use strict";
/**
 * SPECLANG-GENERATED: Python code templates
 * Source: @speclang/compiler.spec.dir/python
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PYTHON_TEMPLATES = void 0;
exports.renderPythonTemplate = renderPythonTemplate;
exports.PYTHON_TEMPLATES = {
    fileHeader: `#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Code generated by SpecLang. DO NOT EDIT.
# Source: {{source}}
# Generated: {{timestamp}}

"""{{docstring}}"""
`,
    dataclass: `@dataclass
class {{name}}:
{{fields}}
`,
    dataclassField: `    {{name}}: {{type}} = {{default}}`,
    pydanticModel: `class {{name}}(BaseModel):
{{fields}}
`,
    pydanticField: `    {{name}}: {{type}} = Field({{fieldArgs}})`,
    function: `def {{name}}({{params}}) -> {{returnType}}:
    """{{docstring}}"""
{{body}}
`,
    asyncFunction: `async def {{name}}({{params}}) -> {{returnType}}:
    """{{docstring}}"""
{{body}}
`,
    class: `class {{name}}:
    """{{docstring}}"""
{{body}}
`,
    classWithBase: `class {{name}}({{bases}}):
    """{{docstring}}"""
{{body}}
`,
    method: `    def {{name}}(self, {{params}}) -> {{returnType}}:
        """{{docstring}}"""
{{body}}
`,
    property: `    @property
    def {{name}}(self) -> {{returnType}}:
{{body}}
`,
    enum: `class {{name}}(str, Enum):
{{values}}
`,
    enumValue: `    {{name}} = "{{value}}"`,
    protocol: `class {{name}}(Protocol):
{{methods}}
`,
    protocolMethod: `    def {{name}}(self, {{params}}) -> {{returnType}}: ...`,
    exception: `class {{name}}Error(Exception):
    def __init__(self, message: str, code: str | None = None):
        self.message = message
        self.code = code
        super().__init__(self.message)
`,
    fastapiRoute: `@router.{{method}}("{{path}}")
async def {{handlerName}}({{params}}) -> {{returnType}}:
{{body}}
`,
    importBlock: `{{imports}}
`,
    importSingle: `import {{module}}`,
    importFrom: `from {{module}} import {{names}}`,
    fieldInit: `{{name}}={{value}},`,
};
function renderPythonTemplate(template, vars) {
    let result = template;
    for (const [key, value] of Object.entries(vars)) {
        result = result.replace(new RegExp(`{{${key}}}`, 'g'), value);
    }
    return result;
}
//# sourceMappingURL=templates.js.map