/**
 * SPECLANG-GENERATED - Do not edit directly
 * 
 * Source: specs/safety.spec.dir/src/quarantine.spec.md
 * Generated: 2026-03-21
 * 
 * Edit the spec, not this file.
 */

export interface QuarantineTicket {
  id: string;
  specId: string;
  reason: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  status: 'open' | 'approved' | 'released' | 'expired';
  createdAt: string;
  expiresAt: string;
  approvedBy: string | null;
  approvedAt: string | null;
  releaseReason: string | null;
  autoGenerated: boolean;
}

export class QuarantineManager {
  private tickets: Map<string, QuarantineTicket> = new Map();
  
  constructor() {
    // No database for now
  }

  async createTicket(data: {
    specId: string;
    reason: string;
    severity: QuarantineTicket['severity'];
    autoGenerated: boolean;
  }): Promise<QuarantineTicket> {
    const ticket: QuarantineTicket = {
      id: this.generateId(),
      specId: data.specId,
      reason: data.reason,
      severity: data.severity,
      status: 'open',
      createdAt: new Date().toISOString(),
      expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(), // 24 hours
      approvedBy: null,
      approvedAt: null,
      releaseReason: null,
      autoGenerated: data.autoGenerated,
    };
    
    this.tickets.set(ticket.id, ticket);
    
    // Persist to database (placeholder)
    
    return ticket;
  }

  async approve(ticketId: string, approver: string): Promise<void> {
    const ticket = this.tickets.get(ticketId);
    if (!ticket) throw new Error(`Ticket ${ticketId} not found`);
    
    ticket.status = 'approved';
    ticket.approvedBy = approver;
    ticket.approvedAt = new Date().toISOString();
    
    // Database update placeholder
  }

  async release(ticketId: string, releaser: string, reason?: string): Promise<void> {
    const ticket = this.tickets.get(ticketId);
    if (!ticket) throw new Error(`Ticket ${ticketId} not found`);
    
    ticket.status = 'released';
    ticket.releaseReason = reason || 'Manually released';
    
    // Database update placeholder
  }

  async getOpenTickets(): Promise<QuarantineTicket[]> {
    return Array.from(this.tickets.values()).filter(t => t.status === 'open');
  }

  async getTicketsForSpec(specId: string): Promise<QuarantineTicket[]> {
    return Array.from(this.tickets.values()).filter(t => t.specId === specId);
  }

  private generateId(): string {
    return `QT-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
  }
}