/**
 * E2E Test: Spec-to-Code Cascade
 * 
 * Tests the complete end-to-end flow from spec creation to code generation
 * as described in TODO.md Phase 5: Integration Tests
 */

import { describe, it, expect, beforeAll, afterAll, beforeEach, afterEach } from 'vitest';
import { existsSync, readFileSync, writeFileSync, mkdirSync, rmSync } from 'fs';
import { join } from 'path';
import { execSync } from 'child_process';

const TEST_DIR = join(process.cwd(), 'test-spec-to-code-output');
const SPECS_DIR = join(TEST_DIR, 'specs');
const GENERATED_DIR = join(TEST_DIR, 'generated');

describe('E2E: Spec-to-Code Cascade', () => {
  beforeAll(() => {
    // Create test directories
    mkdirSync(TEST_DIR, { recursive: true });
    mkdirSync(SPECS_DIR, { recursive: true });
    mkdirSync(GENERATED_DIR, { recursive: true });
  });

  afterAll(() => {
    // Clean up test directories
    if (existsSync(TEST_DIR)) {
      rmSync(TEST_DIR, { recursive: true, force: true });
    }
  });

  describe('Step 1: Spec Creation', () => {
    it('should create a simple spec file', () => {
      const specContent = `# speclang-header lines:12
id: "@test/simple"
version: 1.0.0
layer: 5
short: "Simple test spec"
tags: [test, e2e]
---

# Simple Spec

Simple test spec for E2E testing.

### @block::add @kind:function

Adds two numbers.

**Parameters:**
- a: number - First number
- b: number - Second number

**Returns:** number - Sum of a and b

\`\`\`typescript
export function add(a: number, b: number): number {
  return a + b;
}
\`\`\`
`;

      const specPath = join(SPECS_DIR, 'simple.spec.md');
      writeFileSync(specPath, specContent, 'utf-8');

      expect(existsSync(specPath)).toBe(true);
      
      const content = readFileSync(specPath, 'utf-8');
      expect(content).toContain('# speclang-header');
      expect(content).toContain('id: "@test/simple"');
      expect(content).toContain('### @block::add @kind:function');
    });
  });

  describe('Step 2: Cascade Execution', () => {
    it('should run cascade on spec file', () => {
      const specPath = join(SPECS_DIR, 'simple.spec.md');
      expect(existsSync(specPath)).toBe(true);

      // Run cascade command
      const result = execSync(
        `node ${join(process.cwd(), 'bin/speclang')} cascade ${specPath}`,
        { cwd: TEST_DIR, encoding: 'utf-8' }
      );

      expect(result).toContain('Cascade complete');
      expect(result).toContain('Generated:');
    });
  });

  describe('Step 3: Generated Code Verification', () => {
    it('should have generated TypeScript file', () => {
      // Cascade generates files in generated/ directory relative to spec location
      // Since we ran cascade with cwd=TEST_DIR, files should be in TEST_DIR/generated/
      // Note: block name includes colon due to double colon syntax
      const generatedFile = join(GENERATED_DIR, ':add.ts');
      expect(existsSync(generatedFile)).toBe(true);

      const content = readFileSync(generatedFile, 'utf-8');
      expect(content).toContain('Auto-generated by SpecLang');
      expect(content).toContain('Source: "@test/simple"');
      expect(content).toContain('export function add');
      expect(content).toContain('a: number, b: number');
      expect(content).toContain('return a + b');
    });
  });

  describe('Spec Edit → Cascade → Updated Code', () => {
    const specName = 'edit-test.spec.md';
    const specPath = join(SPECS_DIR, specName);
    const generatedFileName = ':multiply.ts';
    const generatedFilePath = join(GENERATED_DIR, generatedFileName);

    beforeEach(() => {
      // Clean up previous generated file
      if (existsSync(generatedFilePath)) {
        rmSync(generatedFilePath);
      }
    });

    it('should generate code from initial spec', () => {
      const specContent = `# speclang-header lines:12
id: "@test/edit"
version: 1.0.0
layer: 5
short: "Edit test spec"
tags: [test, e2e]
---

# Edit Test Spec

### @block::multiply @kind:function

Multiplies two numbers.

**Parameters:**
- x: number - First factor
- y: number - Second factor

**Returns:** number - Product

\`\`\`typescript
export function multiply(x: number, y: number): number {
  return x * y;
}
\`\`\`
`;

      writeFileSync(specPath, specContent, 'utf-8');
      expect(existsSync(specPath)).toBe(true);

      // Run cascade
      const result = execSync(
        `node ${join(process.cwd(), 'bin/speclang')} cascade ${specPath}`,
        { cwd: TEST_DIR, encoding: 'utf-8' }
      );
      expect(result).toContain('Cascade complete');

      // Verify generated file
      expect(existsSync(generatedFilePath)).toBe(true);
      const content = readFileSync(generatedFilePath, 'utf-8');
      expect(content).toContain('export function multiply');
      expect(content).toContain('return x * y');
    });

    it('should update generated code when spec is edited', () => {
      // Ensure spec exists (from previous test)
      if (!existsSync(specPath)) {
        // Recreate spec
        const specContent = `# speclang-header lines:12
id: "@test/edit"
version: 1.0.0
layer: 5
short: "Edit test spec"
tags: [test, e2e]
---

# Edit Test Spec

### @block::multiply @kind:function

Multiplies two numbers.

**Parameters:**
- x: number - First factor
- y: number - Second factor

**Returns:** number - Product

\`\`\`typescript
export function multiply(x: number, y: number): number {
  return x * y;
}
\`\`\`
`;
        writeFileSync(specPath, specContent, 'utf-8');
      }

      // Edit spec: change implementation
      const originalContent = readFileSync(specPath, 'utf-8');
      const editedContent = originalContent.replace(
        'return x * y;',
        'return x * y * 2; // Double product'
      );
      writeFileSync(specPath, editedContent, 'utf-8');

      // Run cascade again
      const result = execSync(
        `node ${join(process.cwd(), 'bin/speclang')} cascade ${specPath}`,
        { cwd: TEST_DIR, encoding: 'utf-8' }
      );
      expect(result).toContain('Cascade complete');

      // Verify generated file updated
      expect(existsSync(generatedFilePath)).toBe(true);
      const content = readFileSync(generatedFilePath, 'utf-8');
      expect(content).toContain('return x * y * 2; // Double product');
    });
  });

  describe('Spec Validation → Error Detection', () => {
    const invalidSpecPath = join(SPECS_DIR, 'invalid.spec.md');

    beforeEach(() => {
      // Clean up previous invalid spec
      if (existsSync(invalidSpecPath)) {
        rmSync(invalidSpecPath);
      }
    });

    it('should detect missing required header fields', () => {
      const specContent = `# speclang-header lines:3
id: "@test/invalid"
---
# Invalid spec missing version
`;

      writeFileSync(invalidSpecPath, specContent, 'utf-8');

      // Run validate command
      const result = execSync(
        `node ${join(process.cwd(), 'bin/speclang')} validate ${invalidSpecPath}`,
        { cwd: TEST_DIR, encoding: 'utf-8', stdio: 'pipe' }
      );

      // Validate should report failure
      expect(result).toContain('Failed: 1');
      expect(result).toContain('Errors: 1');
    });

    it('should detect broken references', () => {
      const specContent = `# speclang-header lines:10
id: "@test/broken-ref"
version: 1.0.0
layer: 5
short: "Broken ref spec"
tags: [test]
---

# Broken Ref Spec

This spec references a non-existent spec.

@ref:specs/nonexistent
`;

      writeFileSync(invalidSpecPath, specContent, 'utf-8');

      // Run validate command with --strict
      const result = execSync(
        `node ${join(process.cwd(), 'bin/speclang')} validate ${invalidSpecPath} --strict`,
        { cwd: TEST_DIR, encoding: 'utf-8', stdio: 'pipe' }
      );

      // Validate should report broken reference
      expect(result).toContain('Failed: 1');
      expect(result).toContain('Errors: 1');
    });
  });

  describe('Full Project Initialization Flow', () => {
    const projectDir = join(TEST_DIR, 'my-project');

    beforeEach(() => {
      // Clean up previous project
      if (existsSync(projectDir)) {
        rmSync(projectDir, { recursive: true, force: true });
      }
    });

    it('should create new project with speclang new', () => {
      // Run speclang new command
      const result = execSync(
        `node ${join(process.cwd(), 'bin/speclang')} new my-project`,
        { cwd: TEST_DIR, encoding: 'utf-8', stdio: 'pipe' }
      );

      expect(result).toContain('Creating new speclang project');
      expect(existsSync(projectDir)).toBe(true);

      // Check essential files exist
      expect(existsSync(join(projectDir, '.speclangrc'))).toBe(true);
      expect(existsSync(join(projectDir, 'specs'))).toBe(true);
      expect(existsSync(join(projectDir, 'specs', 'main.spec.md'))).toBe(true);
      expect(existsSync(join(projectDir, 'src'))).toBe(true);
      expect(existsSync(join(projectDir, 'tests'))).toBe(true);
    });

    it('should generate code from default spec', () => {
      // First create project
      execSync(
        `node ${join(process.cwd(), 'bin/speclang')} new my-project`,
        { cwd: TEST_DIR, encoding: 'utf-8', stdio: 'pipe' }
      );

      // Run cascade on default spec
      const specPath = join(projectDir, 'specs', 'main.spec.md');
      expect(existsSync(specPath)).toBe(true);

      const result = execSync(
        `node ${join(process.cwd(), 'bin/speclang')} cascade ${specPath}`,
        { cwd: projectDir, encoding: 'utf-8', stdio: 'pipe' }
      );

      expect(result).toContain('Cascade complete');
      // Check generated files exist
      expect(existsSync(join(projectDir, 'generated'))).toBe(true);
    });
  });
});