import { describe, it, expect } from "vitest";
import { getDefaultConfig } from "../src/config/loader.js";
import { validateConfig } from "../src/config/validator.js";
import { DEFAULT_WATCHER_CONFIG } from "../src/config/schema.js";

describe("Configuration System", () => {
  describe("Default Configuration", () => {
    it("should return default config with correct structure", () => {
      const config = getDefaultConfig();
      expect(config).toHaveProperty("metadata");
      expect(config.metadata).toHaveProperty("name", "Unnamed Project");
      expect(config.metadata).toHaveProperty("version", "0.1.0");
      expect(config.metadata).toHaveProperty(
        "description",
        "Generated by SpecLang",
      );
      expect(config.targets).toEqual(["typescript"]);
      expect(config.config.watcher).toEqual(DEFAULT_WATCHER_CONFIG);
    });
  });

  describe("Validation", () => {
    it("should validate correct default config", () => {
      const config = getDefaultConfig();
      const result = validateConfig(config);
      expect(result.valid).toBe(true);
      expect(result.errors).toEqual([]);
    });

    it("should reject invalid language in targets", () => {
      const config = getDefaultConfig();
      config.targets = ["invalid" as any];
      const result = validateConfig(config);
      expect(result.valid).toBe(false);
      expect(result.errors).toContainEqual(
        expect.objectContaining({
          path: "targets[0]",
          message: expect.stringContaining("Invalid language"),
        }),
      );
    });

    it("should reject negative debounce", () => {
      const config = getDefaultConfig();
      config.config.watcher.debounce = -100;
      const result = validateConfig(config);
      expect(result.valid).toBe(false);
      expect(result.errors).toContainEqual(
        expect.objectContaining({
          path: "config.watcher.debounce",
          message: expect.stringContaining("non-negative"),
        }),
      );
    });

    it("should reject invalid split strategy", () => {
      const config = getDefaultConfig();
      (config.config.split as any).strategy = "invalid";
      const result = validateConfig(config);
      expect(result.valid).toBe(false);
      expect(result.errors).toContainEqual(
        expect.objectContaining({
          path: "config.split.strategy",
          message: expect.stringContaining("Strategy must be one of"),
        }),
      );
    });

    it("should accept valid custom config", () => {
      const config = getDefaultConfig();
      config.metadata.name = "My Project";
      config.targets = ["typescript", "python"];
      config.config.watcher.debounce = 500;
      config.config.split.max_tokens = 20000;
      const result = validateConfig(config);
      expect(result.valid).toBe(true);
    });
  });
});
