// SPECLANG-GENERATED: This file was generated by the speclang-code-gen agent
// Source: @speclang/test-specs
// DO NOT EDIT MANUALLY

// speclang-header lines:12
// id: @speclang/test-specs
// version: 0.1.0
// layer: 0
// tags: [tests, bdd, natural-language]
// imports: [@speclang/core]
// status: draft
// short: Test Specs
// @ref: @speclang/test-specs/format
// @ref: @speclang/test-specs/examples
// ---

import { describe, it, expect, beforeAll } from "vitest";
import * as path from "path";
import * as fs from "fs/promises";
import type { TestSpec, TestScenario } from "../src/test-specs";
import {
  TestSpecParser,
  TestGenerator,
  TestRunner,
  TestSpecReporter,
  TestResultSync,
} from "../src/test-specs";

// Sample test spec content for parsing tests
const sampleTestSpec = `# speclang-header lines:12
id: "@tests/auth/login"
version: 1.0.0
layer: 4
target: "@specs/auth#login"
tags: [auth, login, critical]
short: Login flow tests
---

# Login Tests

Tests for the authentication login flow.

## Scenario: Successful login with valid credentials

Given: a registered user with email "user@example.com"
Given: the user has password "correct-password"
When: the user submits login with email "user@example.com" and password "correct-password"
Then: the system returns a valid JWT token
Then: the token expires in 24 hours

## Scenario: Login fails with wrong password

Given: a registered user with email "user@example.com"
Given: the user has password "correct-password"
When: the user submits login with email "user@example.com" and password "wrong-password"
Then: the system returns 401 Unauthorized
Then: the error message is "Invalid credentials"

## Scenario: Parameterized password validation

Given: a password validation function
When: the password is validated
Then: validation result is correct

| password | is_valid | reason |
|----------|----------|--------|
| Abc123!@ | true | meets all requirements |
| abc123 | false | missing uppercase and special |
| ABCDEF | false | missing lowercase and numbers |
`;

describe("TestSpecParser", () => {
  let parser: TestSpecParser;

  beforeAll(() => {
    parser = new TestSpecParser();
  });

  it("should parse test spec with scenarios", () => {
    const spec = parser.parse(sampleTestSpec);

    expect(spec.id).toBe("@tests/auth/login");
    expect(spec.version).toBe("1.0.0");
    expect(spec.target).toBe("@specs/auth#login");
    expect(spec.tags).toEqual(["auth", "login", "critical"]);
    expect(spec.scenarios).toHaveLength(3);
  });

  it("should parse scenario with given/when/then", () => {
    const spec = parser.parse(sampleTestSpec);
    const scenario = spec.scenarios[0];

    expect(scenario.name).toBe("Successful login with valid credentials");
    expect(scenario.given).toHaveLength(2);
    expect(scenario.given[0]).toContain("registered user");
    expect(scenario.when).toContain("submits login");
    expect(scenario.then).toHaveLength(2);
    expect(scenario.then[0]).toContain("JWT token");
  });

  it("should parse parameterized tests with examples", () => {
    const spec = parser.parse(sampleTestSpec);
    const scenario = spec.scenarios[2];

    expect(scenario.examples).toBeDefined();
    expect(scenario.examples?.headers).toEqual([
      "password",
      "is_valid",
      "reason",
    ]);
    expect(scenario.examples?.rows).toHaveLength(3);
    expect(scenario.examples?.rows[0]).toEqual([
      "Abc123!@",
      "true",
      "meets all requirements",
    ]);
  });

  it("should throw error for invalid spec without header", () => {
    expect(() => {
      parser.parse("# No header here\n## Scenario: Test");
    }).toThrow("No YAML header found");
  });

  it("should throw error for spec without id", () => {
    expect(() => {
      parser.parse(`---
version: 1.0.0
---

# Test`);
    }).toThrow("must have an id");
  });
});

describe("TestGenerator", () => {
  let parser: TestSpecParser;
  let generator: TestGenerator;

  beforeAll(() => {
    parser = new TestSpecParser();
    generator = new TestGenerator();
  });

  it("should generate TypeScript test code", () => {
    const spec = parser.parse(sampleTestSpec);
    const code = generator.generate(spec, "typescript");

    expect(code).toContain("@speclang-generated");
    expect(code).toContain("describe('Login flow tests'");
    expect(code).toContain("it('Successful login");
    expect(code).toContain("expect(result.token).toBeDefined()");
  });

  it("should generate Python test code", () => {
    const spec = parser.parse(sampleTestSpec);
    const code = generator.generate(spec, "python");

    expect(code).toContain("# @speclang-generated");
    expect(code).toContain("class TestLoginflowtests");
    expect(code).toContain("def test_successful_login");
  });

  it("should generate Go test code", () => {
    const spec = parser.parse(sampleTestSpec);
    const code = generator.generate(spec, "go");

    expect(code).toContain("// @speclang-generated");
    expect(code).toContain("func TestLoginflowtests");
    expect(code).toContain('t.Run("Successful login with valid credentials"');
  });

  it("should generate parameterized tests", () => {
    const spec = parser.parse(sampleTestSpec);
    const code = generator.generate(spec, "typescript");

    expect(code).toContain("describe('Parameterized password validation'");
    expect(code).toContain("params.password");
    expect(code).toContain("'Abc123!@'");
  });

  it("should translate Given to setup code", () => {
    const spec = parser.parse(sampleTestSpec);
    const code = generator.generate(spec, "typescript");

    // Check that "registered user" is translated
    expect(code).toContain("email: 'user@example.com'");
  });

  it("should translate When to action code", () => {
    const spec = parser.parse(sampleTestSpec);
    const code = generator.generate(spec, "typescript");

    // Check that login action is translated
    expect(code).toContain(
      "await login('user@example.com', 'correct-password')",
    );
  });

  it("should translate Then to assertions", () => {
    const spec = parser.parse(sampleTestSpec);
    const code = generator.generate(spec, "typescript");

    // Check JWT assertion
    expect(code).toContain("expect(result.token).toBeDefined()");
    // Check 401 assertion
    expect(code).toContain("expect(result.status).toBe(401)");
    // Check error message assertion
    expect(code).toContain("expect(result.error).toBe('Invalid credentials')");
  });
});

describe("TestSpecReporter", () => {
  let reporter: TestSpecReporter;

  beforeAll(() => {
    reporter = new TestSpecReporter();
  });

  it("should format a test report", () => {
    const report = {
      specId: "@tests/auth/login",
      totalScenarios: 3,
      passed: 2,
      failed: 1,
      skipped: 0,
      duration: 150,
      results: [
        {
          specId: "@tests/auth/login",
          scenarioName: "Successful login",
          status: "passed" as const,
          duration: 50,
          timestamp: Date.now(),
        },
        {
          specId: "@tests/auth/login",
          scenarioName: "Wrong password",
          status: "failed" as const,
          duration: 100,
          error: "Expected 401, got 500",
          timestamp: Date.now(),
        },
      ],
    };

    const output = reporter.formatReport(report);

    expect(output).toContain("Test Report: @tests/auth/login");
    expect(output).toContain("Passed: 2");
    expect(output).toContain("Failed: 1");
    expect(output).toContain("✓ Successful login");
    expect(output).toContain("✗ Wrong password");
    expect(output).toContain("Expected 401, got 500");
  });

  it("should format a summary of multiple reports", () => {
    const reports = [
      {
        specId: "@tests/auth/login",
        totalScenarios: 3,
        passed: 2,
        failed: 1,
        skipped: 0,
        duration: 150,
        results: [],
      },
      {
        specId: "@tests/auth/logout",
        totalScenarios: 2,
        passed: 2,
        failed: 0,
        skipped: 0,
        duration: 50,
        results: [],
      },
    ];

    const output = reporter.formatSummary(reports);

    expect(output).toContain("Specs: 2");
    expect(output).toContain("Scenarios: 5");
    expect(output).toContain("Passed: 4");
    expect(output).toContain("Failed: 1");
  });

  it("should format failures only", () => {
    const reports = [
      {
        specId: "@tests/auth/login",
        totalScenarios: 2,
        passed: 1,
        failed: 1,
        skipped: 0,
        duration: 100,
        results: [
          {
            specId: "@tests/auth/login",
            scenarioName: "Failed scenario",
            status: "failed" as const,
            duration: 50,
            error: "Test error",
            timestamp: Date.now(),
          },
        ],
      },
    ];

    const output = reporter.formatFailures(reports);

    expect(output).toContain("Failed Tests");
    expect(output).toContain("✗ Failed scenario");
    expect(output).toContain("Test error");
  });

  it("should get summary statistics", () => {
    const reports = [
      {
        specId: "@tests/auth/login",
        totalScenarios: 3,
        passed: 2,
        failed: 1,
        skipped: 0,
        duration: 150,
        results: [],
      },
    ];

    const stats = reporter.getSummaryStats(reports);

    expect(stats.totalSpecs).toBe(1);
    expect(stats.totalScenarios).toBe(3);
    expect(stats.totalPassed).toBe(2);
    expect(stats.totalFailed).toBe(1);
    expect(stats.passRate).toBeCloseTo(66.67, 1);
  });

  it("should format JSON output", () => {
    const report = {
      specId: "@tests/auth/login",
      totalScenarios: 1,
      passed: 1,
      failed: 0,
      skipped: 0,
      duration: 100,
      results: [],
    };

    const json = reporter.formatJson(report);
    const parsed = JSON.parse(json);

    expect(parsed.specId).toBe("@tests/auth/login");
    expect(parsed.passed).toBe(1);
  });
});

describe("TestSpec Integration", () => {
  it("should parse and generate a complete test", () => {
    const parser = new TestSpecParser();
    const generator = new TestGenerator();

    const spec = parser.parse(sampleTestSpec);
    const code = generator.generate(spec, "typescript");

    // Should have all three scenarios
    expect(code).toContain("Successful login");
    expect(code).toContain("Login fails");
    expect(code).toContain("Parameterized");
  });

  it("should handle edge cases in parsing", () => {
    const edgeCaseSpec = `# speclang-header lines:5
id: "@tests/edge"
version: 1.0.0
---

# Edge Cases

## Scenario: Empty

Given: nothing special
When: nothing happens
Then: nothing occurs
`;

    const parser = new TestSpecParser();
    const spec = parser.parse(edgeCaseSpec);

    expect(spec.scenarios).toHaveLength(1);
    expect(spec.scenarios[0].given).toHaveLength(1);
    expect(spec.scenarios[0].when).toContain("nothing happens");
    expect(spec.scenarios[0].then).toHaveLength(1);
  });

  it("should handle scenario with only when and then", () => {
    const minimalSpec = `# speclang-header lines:5
id: "@tests/minimal"
version: 1.0.0
---

## Scenario: Minimal

When: an action occurs
Then: a result is returned
`;

    const parser = new TestSpecParser();
    const spec = parser.parse(minimalSpec);

    expect(spec.scenarios).toHaveLength(1);
    expect(spec.scenarios[0].given).toHaveLength(0);
    expect(spec.scenarios[0].when).toContain("an action occurs");
    expect(spec.scenarios[0].then).toHaveLength(1);
  });
});

describe("Natural Language Translation", () => {
  it("should handle password validation translation", () => {
    const validatorSpec = `# speclang-header lines:5
id: "@tests/validator"
version: 1.0.0
---

## Scenario: Validate password

Given: a password validation function
When: the password is validated
Then: validation result is correct
`;

    const parser = new TestSpecParser();
    const generator = new TestGenerator();

    const spec = parser.parse(validatorSpec);
    const code = generator.generate(spec, "typescript");

    // Should contain validation logic
    expect(code).toContain("validatePassword");
    expect(code).toContain("params.password");
  });

  it("should handle account locking scenarios", () => {
    const lockSpec = `# speclang-header lines:5
id: "@tests/lock"
version: 1.0.0
---

## Scenario: Locked account

Given: a registered user with email "user@test.com"
Given: the user has 4 failed login attempts
When: the user submits login with wrong password
Then: the account is locked for 15 minutes
`;

    const parser = new TestSpecParser();
    const generator = new TestGenerator();

    const spec = parser.parse(lockSpec);
    const code = generator.generate(spec, "typescript");

    expect(code).toContain("Locked for 15 minutes");
  });

  it("should handle token expiry scenarios", () => {
    const expirySpec = `# speclang-header lines:5
id: "@tests/token"
version: 1.0.0
---

## Scenario: Token expiry

Given: a valid JWT token is issued
When: token expires
Then: token expires in 24 hours
`;

    const parser = new TestSpecParser();
    const generator = new TestGenerator();

    const spec = parser.parse(expirySpec);
    const code = generator.generate(spec, "typescript");

    expect(code).toContain("24 * 60 * 60");
  });
});

describe("Error Handling", () => {
  it("should throw on unsupported language", () => {
    const parser = new TestSpecParser();
    const generator = new TestGenerator();
    const spec = parser.parse(sampleTestSpec);

    expect(() => {
      generator.generate(spec, "java" as any);
    }).toThrow("Unsupported language");
  });

  it("should handle empty scenarios gracefully", () => {
    const emptySpec = `# speclang-header lines:5
id: "@tests/empty"
version: 1.0.0
---

# Empty Test
`;

    const parser = new TestSpecParser();
    const spec = parser.parse(emptySpec);

    expect(spec.scenarios).toHaveLength(0);
  });
});
