/**
 * SPECLANG-GENERATED: Go code generator unit tests
 * Source: @speclang/compiler.spec.dir/go
 */

import { describe, it, expect, beforeEach } from 'vitest';
import {
  GoCodeGenerator,
  createGoCodeGenerator,
  type SpecBlock,
  type SpecField,
  type SpecMethod,
} from '../../src/compiler/go/generator';
import {
  renderStruct,
  renderInterface,
  renderConstructor,
  renderImports,
  renderFile,
  type GoFieldDef,
  type GoMethodDef,
} from '../../src/compiler/go/templates';

// ============================================================================
// Template Function Tests
// ============================================================================

describe('renderStruct', () => {
  it('should render a struct with fields and JSON tags', () => {
    const fields: GoFieldDef[] = [
      { name: 'ID', type: 'uint64', tag: '`json:"id"`' },
      { name: 'Email', type: 'string', tag: '`json:"email"`' },
    ];
    const result = renderStruct('User', fields);
    expect(result).toContain('type User struct');
    expect(result).toContain('ID uint64 `json:"id"`');
    expect(result).toContain('Email string `json:"email"`');
  });

  it('should render a struct without tags', () => {
    const fields: GoFieldDef[] = [
      { name: 'Name', type: 'string' },
      { name: 'Age', type: 'int' },
    ];
    const result = renderStruct('Config', fields);
    expect(result).toContain('type Config struct');
    expect(result).toContain('Name string');
    expect(result).toContain('Age int');
  });
});

describe('renderInterface', () => {
  it('should render an interface with methods', () => {
    const methods: GoMethodDef[] = [
      { name: 'FindByID', params: 'id uint64', returns: '*User, error' },
      { name: 'Save', params: 'user *User', returns: '' },
    ];
    const result = renderInterface('UserRepository', methods);
    expect(result).toContain('type UserRepository interface');
    expect(result).toContain('FindByID(id uint64) (*User, error)');
    expect(result).toContain('Save(user *User) ()');
  });
});

describe('renderConstructor', () => {
  it('should render a NewXxx constructor function', () => {
    const fields: GoFieldDef[] = [
      { name: 'Name', type: 'string' },
      { name: 'Age', type: 'int' },
      { name: 'Active', type: 'bool' },
    ];
    const result = renderConstructor('User', fields);
    expect(result).toContain('func NewUser(name string, age int, active bool) *User');
    expect(result).toContain('return &User{');
    expect(result).toContain('Name: name,');
    expect(result).toContain('Age: age,');
    expect(result).toContain('Active: active,');
  });
});

describe('renderImports', () => {
  it('should render a single import', () => {
    const result = renderImports(['fmt']);
    expect(result).toContain('import "fmt"');
  });

  it('should render multiple imports grouped', () => {
    const result = renderImports(['fmt', 'time']);
    expect(result).toContain('import (');
    expect(result).toContain('"fmt"');
    expect(result).toContain('"time"');
    expect(result).toContain(')');
  });

  it('should return empty for no imports', () => {
    expect(renderImports([])).toBe('');
  });
});

describe('renderFile', () => {
  it('should render a complete Go file', () => {
    const body = 'type User struct {\n  Name string\n}\n';
    const result = renderFile('models', ['time'], body, 'user');
    expect(result).toContain('package models');
    expect(result).toContain('import');
    expect(result).toContain('"time"');
    expect(result).toContain('type User struct');
    expect(result).toContain('// Code generated by SpecLang. DO NOT EDIT.');
    expect(result).toContain('// Source: user');
  });
});

// ============================================================================
// GoCodeGenerator Tests
// ============================================================================

describe('GoCodeGenerator', () => {
  let gen: GoCodeGenerator;

  beforeEach(() => {
    gen = createGoCodeGenerator({ packageName: 'testpkg' });
  });

  describe('generateStruct', () => {
    it('should generate a struct with basic types and JSON tags', () => {
      const fields: SpecField[] = [
        { name: 'id', type: 'String' },
        { name: 'email', type: 'String' },
      ];
      const result = gen.generateStruct('User', fields);

      expect(result).toContain('type User struct');
      expect(result).toContain('ID string');
      expect(result).toContain('Email string');
      expect(result).toContain('json:"id"');
      expect(result).toContain('json:"email"');
    });

    it('should generate struct with time and uuid types', () => {
      const fields: SpecField[] = [
        { name: 'id', type: 'UUID' },
        { name: 'createdAt', type: 'DateTime' },
      ];
      const result = gen.generateStruct('AuditLog', fields);

      expect(result).toContain('type AuditLog struct');
      expect(result).toContain('ID uuid.UUID');
      expect(result).toContain('CreatedAt time.Time');
    });

    it('should generate struct with array and optional types', () => {
      const fields: SpecField[] = [
        { name: 'roles', type: 'Array<String>' },
        { name: 'nickname', type: 'Optional<String>' },
      ];
      const result = gen.generateStruct('Profile', fields);

      expect(result).toContain('Roles []string');
      expect(result).toContain('Nickname *string');
    });
  });

  describe('generateConstructor', () => {
    it('should generate NewXxx constructor', () => {
      const fields: SpecField[] = [
        { name: 'name', type: 'String' },
        { name: 'age', type: 'Int' },
      ];
      const result = gen.generateConstructor('Person', fields);

      expect(result).toContain('func NewPerson(name string, age int) *Person');
      expect(result).toContain('Name: name,');
      expect(result).toContain('Age: age,');
    });
  });

  describe('generateInterface', () => {
    it('should generate an interface with methods', () => {
      const methods: SpecMethod[] = [
        {
          name: 'FindByID',
          params: [{ name: 'id', type: 'Int64' }],
          returns: ['string', 'error'],
        },
        {
          name: 'Save',
          params: [{ name: 'data', type: 'String' }],
          returns: ['error'],
        },
      ];
      const result = gen.generateInterface('Repository', methods);

      expect(result).toContain('type Repository interface');
      expect(result).toContain('FindByID(id int64) (string, error)');
      expect(result).toContain('Save(data string) (error)');
    });
  });

  describe('generate', () => {
    it('should generate a complete Go file from a spec block', () => {
      const block: SpecBlock = {
        name: 'User',
        package: 'models',
        fields: [
          { name: 'id', type: 'UUID' },
          { name: 'createdAt', type: 'DateTime' },
          { name: 'email', type: 'String' },
        ],
        methods: [
          {
            name: 'IsValid',
            params: [],
            returns: ['bool'],
          },
        ],
      };

      const result = gen.generate(block);

      expect(result.code).toContain('package models');
      expect(result.code).toContain('import');
      expect(result.code).toContain('"time"');
      expect(result.code).toContain('"github.com/google/uuid"');
      expect(result.code).toContain('type User struct');
      expect(result.code).toContain('ID uuid.UUID');
      expect(result.code).toContain('CreatedAt time.Time');
      expect(result.code).toContain('Email string');
      expect(result.code).toContain('func NewUser');
      expect(result.code).toContain('func (r *User) IsValid() bool');
      expect(result.imports).toContain('time');
      expect(result.imports).toContain('github.com/google/uuid');
      expect(result.package).toBe('models');
    });

    it('should generate a Go file with interfaces', () => {
      const block: SpecBlock = {
        name: 'UserService',
        package: 'services',
        fields: [
          { name: 'repo', type: 'Any' },
        ],
        interfaces: [
          {
            name: 'UserRepository',
            methods: [
              {
                name: 'FindByID',
                params: [{ name: 'id', type: 'Int64' }],
                returns: ['string', 'error'],
              },
            ],
          },
        ],
      };

      const result = gen.generate(block);

      expect(result.code).toContain('package services');
      expect(result.code).toContain('type UserService struct');
      expect(result.code).toContain('type UserRepository interface');
      expect(result.code).toContain('FindByID(id int64) (string, error)');
    });

    it('should generate a Go file without constructor when disabled', () => {
      const genNoConstr = createGoCodeGenerator({
        packageName: 'config',
        addConstructor: false,
      });
      const block: SpecBlock = {
        name: 'Config',
        package: 'config',
        fields: [
          { name: 'timeout', type: 'Int' },
        ],
      };

      const result = genNoConstr.generate(block);
      expect(result.code).toContain('type Config struct');
      expect(result.code).not.toContain('func NewConfig');
    });

    it('should generate valid Go syntax (proper braces, types, formatting)', () => {
      const block: SpecBlock = {
        name: 'ComplexModel',
        package: 'model',
        fields: [
          { name: 'id', type: 'UUID' },
          { name: 'name', type: 'String' },
          { name: 'tags', type: 'Array<String>' },
          { name: 'metadata', type: 'Map<String,String>' },
          { name: 'config', type: 'Optional<String>' },
          { name: 'createdAt', type: 'DateTime' },
          { name: 'updatedAt', type: 'DateTime' },
        ],
      };

      const result = gen.generate(block);

      // Verify brace matching
      const openBraces = (result.code.match(/\{/g) || []).length;
      const closeBraces = (result.code.match(/\}/g) || []).length;
      expect(openBraces).toBe(closeBraces);

      // Verify paren matching
      const openParens = (result.code.match(/\(/g) || []).length;
      const closeParens = (result.code.match(/\)/g) || []).length;
      expect(openParens).toBe(closeParens);

      // Verify proper Go constructs
      expect(result.code).toContain('package model');
      expect(result.code).toContain('import');
      expect(result.code).toContain('type ComplexModel struct');
      expect(result.code).toContain('uuid.UUID');
      expect(result.code).toContain('time.Time');
      expect(result.code).toContain('[]string');
      expect(result.code).toContain('map[string]string');
      expect(result.code).toContain('*string');
      expect(result.code).toContain('func NewComplexModel');

      // Verify all fields present
      expect(result.code).toContain('ID uuid.UUID');
      expect(result.code).toContain('Name string');
      expect(result.code).toContain('Tags []string');
      expect(result.code).toContain('Metadata map[string]string');
      expect(result.code).toContain('Config *string');
      expect(result.code).toContain('CreatedAt time.Time');
      expect(result.code).toContain('UpdatedAt time.Time');
    });
  });

  describe('generateMethods', () => {
    it('should generate method implementations on a struct', () => {
      const methods: SpecMethod[] = [
        {
          name: 'GetName',
          params: [],
          returns: ['string'],
        },
        {
          name: 'SetName',
          params: [{ name: 'name', type: 'String' }],
          returns: [],
        },
      ];
      // generateMethods is private, so test via generate
      const block: SpecBlock = {
        name: 'Widget',
        package: 'widget',
        fields: [{ name: 'name', type: 'String' }],
        methods,
      };

      const result = gen.generate(block);
      expect(result.code).toContain('func (r *Widget) GetName() string');
      expect(result.code).toContain('func (r *Widget) SetName(name string)');
      expect(result.code).toContain('TODO: Implement');
    });
  });
});

describe('createGoCodeGenerator', () => {
  it('should create a GoCodeGenerator with default options', () => {
    const g = createGoCodeGenerator();
    expect(g).toBeInstanceOf(GoCodeGenerator);
    expect(g.language).toBe('go');
    expect(g.extension).toBe('.go');
  });

  it('should create a GoCodeGenerator with custom options', () => {
    const g = createGoCodeGenerator({
      packageName: 'custom',
      addJsonTags: false,
      addConstructor: false,
    });
    const block: SpecBlock = {
      name: 'Test',
      package: 'custom',
      fields: [{ name: 'x', type: 'Int' }],
    };
    const result = g.generate(block);
    expect(result.code).not.toContain('json:');
    expect(result.code).not.toContain('func NewTest');
  });
});
