/**
 * SPECLANG-GENERATED: Go package generator tests
 * Source: @speclang/compiler.spec.dir/go
 */

import { describe, it, expect } from 'vitest';
import {
  GoPackageGenerator,
  createGoPackageGenerator,
  type GoPackageResult,
  type GoGeneratorOptions,
} from '../../src/compiler/go/generator';
import type { SpecBlock, SpecField, SpecMethod, SpecInterface } from '../../src/compiler/go/generator';

describe('GoPackageGenerator', () => {
  const defaultOptions: GoGeneratorOptions = {
    packageName: 'testpkg',
    addJsonTags: true,
    addConstructor: true,
    addInterfaces: true,
  };

  describe('generateFromBlocks', () => {
    it('should generate 3 files from 3 block kinds', () => {
      const gen = createGoPackageGenerator(defaultOptions);

      const userFields: SpecField[] = [
        { name: 'ID', type: 'UUID' },
        { name: 'Name', type: 'String' },
        { name: 'Email', type: 'String' },
      ];

      const repoMethods: SpecMethod[] = [
        {
          name: 'FindByID',
          params: [{ name: 'id', type: 'String' }],
          returns: ['*User', 'error'],
        },
        {
          name: 'Save',
          params: [{ name: 'user', type: 'User' }],
          returns: ['error'],
        },
      ];

      const serviceMethods: SpecMethod[] = [
        {
          name: 'Execute',
          params: [{ name: 'input', type: 'String' }],
          returns: ['*User', 'error'],
        },
      ];

      const blocks: SpecBlock[] = [
        {
          name: 'User',
          kind: 'entity',
          fields: userFields,
        },
        {
          name: 'UserRepository',
          kind: 'interface',
          interfaces: [{ name: 'UserRepository', methods: repoMethods }],
        },
        {
          name: 'CreateUser',
          kind: 'operation',
          methods: serviceMethods,
        },
      ];

      const result: GoPackageResult = gen.generateFromBlocks(blocks, 'testpkg');

      expect(result.pkgName).toBe('testpkg');
      expect(result.files).toHaveLength(3);

      const filenames = result.files.map(f => {
        // Extract filename hint from the generated code's Source comment
        const match = f.code.match(/Source:\s*(.+)/);
        return match ? match[1] : '';
      });

      const modelsFile = result.files.find(f => f.code.includes('Source: models.go'));
      const interfacesFile = result.files.find(f => f.code.includes('Source: interfaces.go'));
      const serviceFile = result.files.find(f => f.code.includes('Source: service.go'));

      expect(modelsFile).toBeDefined();
      expect(interfacesFile).toBeDefined();
      expect(serviceFile).toBeDefined();

      // models.go should have User struct
      expect(modelsFile!.code).toContain('package testpkg');
      expect(modelsFile!.code).toContain('type User struct');
      expect(modelsFile!.code).toContain('ID');
      expect(modelsFile!.code).toContain('Name');
      expect(modelsFile!.code).toContain('Email');

      // interfaces.go should have UserRepository interface
      expect(interfacesFile!.code).toContain('package testpkg');
      expect(interfacesFile!.code).toContain('type UserRepository interface');
      expect(interfacesFile!.code).toContain('FindByID');
      expect(interfacesFile!.code).toContain('Save');
      expect(interfacesFile!.code).toContain('UserRepository interface');

      // service.go should have CreateUser methods
      expect(serviceFile!.code).toContain('package testpkg');
      expect(serviceFile!.code).toContain('func (r *CreateUser) Execute');
      expect(serviceFile!.code).toContain('input string');
    });

    it('should produce compilable Go files with correct structure', () => {
      const gen = createGoPackageGenerator(defaultOptions);

      const fields: SpecField[] = [
        { name: 'ID', type: 'Int64' },
        { name: 'Title', type: 'String' },
      ];

      const methods: SpecMethod[] = [
        {
          name: 'GetTitle',
          params: [],
          returns: ['string'],
        },
      ];

      const blocks: SpecBlock[] = [
        {
          name: 'Todo',
          kind: 'entity',
          fields,
          methods,
        },
        {
          name: 'UserError',
          kind: 'error',
          fields: [
            { name: 'Code', type: 'String' },
            { name: 'Message', type: 'String' },
          ],
        },
      ];

      const result = gen.generateFromBlocks(blocks, 'testpkg');

      expect(result.files.length).toBeGreaterThanOrEqual(2);

      for (const file of result.files) {
        // Every Go file must have a package declaration
        expect(file.code).toMatch(/^\/\/ Code generated by SpecLang/);
        expect(file.code).toContain('package testpkg');
        expect(file.code).toContain('DO NOT EDIT');

        // Must not have duplicate package declarations
        const pkgMatches = (file.code.match(/^package /gm) || []);
        expect(pkgMatches.length).toBe(1);

        // Must have properly closed braces
        const openBraces = (file.code.match(/\{/g) || []).length;
        const closeBraces = (file.code.match(/\}/g) || []).length;
        expect(openBraces).toBe(closeBraces);

        // Verify GeneratedGoCode interface
        expect(file).toHaveProperty('code');
        expect(file).toHaveProperty('imports');
        expect(file).toHaveProperty('package');
        expect(file.package).toBe('testpkg');
      }
    });
  });

  describe('classifyBlock', () => {
    it('should route error blocks to errors.go', () => {
      const gen = createGoPackageGenerator(defaultOptions);

      const blocks: SpecBlock[] = [
        {
          name: 'ValidationError',
          kind: 'error',
          fields: [
            { name: 'Field', type: 'String' },
            { name: 'Message', type: 'String' },
          ],
        },
      ];

      const result = gen.generateFromBlocks(blocks, 'testpkg');
      expect(result.files).toHaveLength(1);
      expect(result.files[0].code).toContain('Source: errors.go');
      expect(result.files[0].code).toContain('type ValidationError struct');
    });

    it('should route blocks with name containing Error to errors.go', () => {
      const gen = createGoPackageGenerator(defaultOptions);

      const blocks: SpecBlock[] = [
        { name: 'ParseError', fields: [{ name: 'Msg', type: 'String' }] },
      ];

      const result = gen.generateFromBlocks(blocks, 'testpkg');
      expect(result.files).toHaveLength(1);
      expect(result.files[0].code).toContain('Source: errors.go');
    });

    it('should combine multiple blocks of the same kind into one file', () => {
      const gen = createGoPackageGenerator(defaultOptions);

      const blocks: SpecBlock[] = [
        { name: 'User', kind: 'entity', fields: [{ name: 'Name', type: 'String' }] },
        { name: 'Product', kind: 'entity', fields: [{ name: 'SKU', type: 'String' }] },
      ];

      const result = gen.generateFromBlocks(blocks, 'testpkg');

      expect(result.files).toHaveLength(1);
      expect(result.files[0].code).toContain('Source: models.go');
      expect(result.files[0].code).toContain('type User struct');
      expect(result.files[0].code).toContain('type Product struct');
    });
  });

  describe('createGoPackageGenerator', () => {
    it('should create instance with default options', () => {
      const gen = createGoPackageGenerator();
      expect(gen).toBeInstanceOf(GoPackageGenerator);
    });

    it('should create instance with custom options', () => {
      const gen = createGoPackageGenerator({
        packageName: 'custom',
        addJsonTags: false,
        addConstructor: false,
      });
      expect(gen).toBeInstanceOf(GoPackageGenerator);
    });
  });
});
