/**
 * SPECLANG-GENERATED - Do not edit directly
 * 
 * Source: specs/project-layout.spec.md
 * Blocks: @block:layout/templates
 * Generated: 2026-02-22
 * 
 * Edit the spec, not this file.
 */

/**
 * Template generation for project layout files
 */

import type {
  ProjectSclTemplateVars,
  SpeclangRcTemplateVars,
  ProjectStructure
} from './types.js';

/**
 * Generate project.scl content from template variables
 */
export function generateProjectScl(vars: ProjectSclTemplateVars): string {
  return `# speclang-header lines:8
id: @northstar
version: ${vars.version}
layer: 0
tags: [northstar, project]
status: draft
---
# North Star

## ${vars.name}

${vars.description}

## Targets
${vars.targets.map(t => `- ${t}`).join('\n')}

## Configuration

### @block:watcher
\`\`\`yaml
patterns:
${vars.watcherPatterns.map(p => `  - "${p}"`).join('\n')}
ignore:
  uses: ".gitignore"
  plus: ${JSON.stringify(vars.watcherIgnore)}
debounce: ${vars.debounce}
\`\`\`

### @block:split
\`\`\`yaml
max_tokens: ${vars.splitMaxTokens}
max_lines: ${vars.splitMaxLines}
strategy: ${vars.splitStrategy}
\`\`\`

### @block:embeddings
\`\`\`yaml
enabled: ${vars.embeddingsEnabled}
model: "${vars.embeddingsModel}"
\`\`\`

### @block:database
\`\`\`yaml
mode: ${vars.databaseMode}
\`\`\`

### @block:cascade
\`\`\`yaml
quiet_period: ${vars.cascadeQuietPeriod}
max_depth: ${vars.cascadeMaxDepth}
\`\`\`
`;
}

/**
 * Generate .speclangrc content from template variables
 */
export function generateSpeclangRc(vars: SpeclangRcTemplateVars): string {
  return `# Speclang Project Configuration
# Generated by speclang init

version: 1
project_root: ${vars.projectRoot}
spec_dirs:
${vars.specDirs.map(d => `  - ${d}`).join('\n')}
generated_dir: ${vars.generatedDir}
daemon:
  enabled: ${vars.daemonEnabled}
  quiet_period: ${vars.daemonQuietPeriod}
`;
}

/**
 * Generate .gitignore content
 */
export function generateGitignore(): string {
  return `# Generated code (can be regenerated)
generated/

# Speclang internal state
.speclang/

# Standard ignores
node_modules/
.env
*.log

# OS files
.DS_Store
Thumbs.db

# IDE
.vscode/
.idea/
*.swp
*.swo

# Test coverage
coverage/
.nyc_output/
`;
}

/**
 * Generate initial spec file for a new project
 */
export function generateInitialSpec(name: string): string {
  const safeName = name.replace(/[^a-zA-Z0-9-]/g, '-').toLowerCase();
  return `# speclang-header lines:10
id: @specs/${safeName}
version: 0.1.0
layer: 1
tags: [feature, ${safeName}]
status: draft
short: Initial feature spec for ${name}
---
# ${name} Feature

## Overview

This is the initial spec file for the ${name} feature.

## Entities

### @block:${safeName}-entity
\`\`\`typescript
interface ${pascalCase(name)} {
  id: string;
  createdAt: Date;
  updatedAt: Date;
}
\`\`\`

## Operations

### @block:${safeName}-create
Create a new ${name} entity.

**Given**: Valid ${name} data
**When**: Create request is made
**Then**: Return new ${name} with generated ID
`;
}

/**
 * Generate initial test spec file
 */
export function generateInitialTestSpec(name: string): string {
  const safeName = name.replace(/[^a-zA-Z0-9-]/g, '-').toLowerCase();
  return `# speclang-header lines:10
id: @tests/${safeName}
version: 0.1.0
layer: 1
tags: [test, ${safeName}]
status: draft
short: Tests for ${name} feature
---
# ${name} Feature Tests

## Test Suite

### @block:${safeName}-create-success
**Given**: Valid ${name} data
**When**: Creating a new ${name}
**Then**: Should return the created ${name} with id

### @block:${safeName}-create-invalid
**Given**: Invalid ${name} data
**When**: Creating a new ${name}
**Then**: Should throw validation error
`;
}

/**
 * Simple PascalCase helper (avoiding external dependencies)
 */
function pascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}

/**
 * Get default template variables for project.scl
 */
export function getDefaultProjectSclVars(name: string): ProjectSclTemplateVars {
  return {
    name,
    version: '0.1.0',
    description: `Project created with speclang init`,
    targets: ['typescript'],
    watcherPatterns: [
      '**/*.spec.{md,yaml,yml,scl}',
      '**/*.{go,ts,js,py,rs,java}.spec',
      '**/project.scl',
      '**/build.{scl,yaml}'
    ],
    watcherIgnore: ['.speclang/', '*.log', 'reports/', '.git/'],
    debounce: 100,
    splitMaxTokens: 10000,
    splitMaxLines: 800,
    splitStrategy: 'smart',
    embeddingsEnabled: true,
    embeddingsModel: 'openai/text-embedding-3-small',
    databaseMode: 'WAL',
    cascadeQuietPeriod: 30,
    cascadeMaxDepth: 50
  };
}

/**
 * Get default template variables for .speclangrc
 */
export function getDefaultSpeclangRcVars(projectRoot: string = '.'): SpeclangRcTemplateVars {
  return {
    projectRoot,
    specDirs: ['specs/', 'tests/'],
    generatedDir: 'generated/',
    daemonEnabled: true,
    daemonQuietPeriod: '30s'
  };
}
