/**
speclang-header lines:5
id: @specs/test-specs
version: 1.0.0
layer: 5
 */

// SPECLANG-GENERATED: This file was generated by the speclang-code-gen agent
// Source: @speclang/test-specs/generator
// DO NOT EDIT MANUALLY

// speclang-header lines:12
// id: @speclang/test-specs/generator
// version: 0.1.0
// layer: 1
// tags: [tests, bdd, generator]
// imports: [@speclang/core]
// status: draft
// short: Test Generator
// @ref: @speclang/test-specs
// @ref: @speclang/test-specs/format
// ---

import { TestSpec, TestScenario, SupportedLanguage } from './types';

/**
 * TestGenerator converts TestSpec objects to executable test code
 * in various programming languages.
 */
export class TestGenerator {
  /**
   * Generate test code for a given test spec and target language
   */
  generate(testSpec: TestSpec, language: SupportedLanguage): string {
    switch (language) {
      case 'typescript':
        return this.generateTypeScript(testSpec);
      case 'python':
        return this.generatePython(testSpec);
      case 'go':
        return this.generateGo(testSpec);
      default:
        throw new Error(`Unsupported language: ${language}`);
    }
  }

  /**
   * Generate TypeScript test code using bun:test
   */
  private generateTypeScript(spec: TestSpec): string {
    const lines: string[] = [];

    lines.push(`// @speclang-generated from ${spec.id}`);
    lines.push(`// @speclang-target ${spec.target}`);
    lines.push('');
    lines.push(`import { describe, it, expect } from 'bun:test';`);
    lines.push('');
    lines.push(`describe('${this.formatDescribe(spec)}', () => {`);

    for (const scenario of spec.scenarios) {
      if (scenario.examples) {
        lines.push(this.generateParameterizedTest(scenario));
      } else {
        lines.push(this.generateStandardTest(scenario));
      }
    }

    lines.push('});');

    return lines.join('\n');
  }

  /**
   * Generate a standard (non-parameterized) test case
   */
  private generateStandardTest(scenario: TestScenario): string {
    const lines: string[] = [];

    lines.push(`  it('${scenario.name}', async () => {`);

    // Given (setup)
    for (const given of scenario.given) {
      lines.push(`    // Given: ${given}`);
      const setupCode = this.translateGiven(given);
      if (setupCode) {
        lines.push(`    ${setupCode}`);
      }
    }

    if (scenario.given.length > 0) {
      lines.push('');
    }

    // When (action)
    lines.push(`    // When: ${scenario.when}`);
    const actionCode = this.translateWhen(scenario.when);
    if (actionCode) {
      lines.push(`    ${actionCode}`);
    }

    lines.push('');

    // Then (assertions)
    for (const then of scenario.then) {
      lines.push(`    // Then: ${then}`);
      const assertCode = this.translateThen(then);
      if (assertCode) {
        lines.push(`    ${assertCode}`);
      }
    }

    lines.push('  });');
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Generate a parameterized test case using examples table
   */
  private generateParameterizedTest(scenario: TestScenario): string {
    const lines: string[] = [];

    lines.push(`  describe('${scenario.name}', () => {`);

    for (const row of scenario.examples!.rows) {
      const testName = row.join(' - ');
      lines.push(`    it('${testName}', async () => {`);

      // Generate test using row values
      lines.push(`      const params = {`);
      for (let i = 0; i < scenario.examples!.headers.length; i++) {
        lines.push(`        ${scenario.examples!.headers[i]}: ${this.formatValue(row[i])},`);
      }
      lines.push(`      };`);

      const whenCode = this.translateWhen(scenario.when);
      if (whenCode) {
        lines.push(`      ${whenCode}`);
      }

      const thenCode = this.translateThen(scenario.then[0]);
      if (thenCode) {
        lines.push(`      ${thenCode}`);
      }

      lines.push(`    });`);
    }

    lines.push('  });');
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Translate natural language Given to setup code
   */
  private translateGiven(given: string): string {
    // "a registered user with email X"
    if (given.includes('registered user')) {
      const emailMatch = given.match(/email "([^"]+)"/);
      const email = emailMatch ? emailMatch[1] : 'test@example.com';
      return `const user = { email: '${email}' }; // TODO: Create actual test user`;
    }

    // "the user has password X"
    if (given.includes('password')) {
      const passwordMatch = given.match(/password "([^"]+)"/);
      if (passwordMatch) {
        return `const password = '${passwordMatch[1]}';`;
      }
    }

    // "the user has N failed login attempts"
    if (given.includes('failed login attempts')) {
      const countMatch = given.match(/(\d+) failed/);
      const count = countMatch ? countMatch[1] : '0';
      return `// Failed attempts: ${count}`;
    }

    // "a password validation function"
    if (given.includes('password validation function')) {
      return `const validatePassword = (pwd: string) => pwd.length >= 8; // TODO: Implement`;
    }

    return ''; // No setup code needed
  }

  /**
   * Translate natural language When to action code
   */
  private translateWhen(when: string): string {
    // "the user submits login with email X and password Y"
    if (when.includes('submits login')) {
      const emailMatch = when.match(/email "([^"]+)"/);
      const passwordMatch = when.match(/password "([^"]+)"/);
      const email = emailMatch ? emailMatch[1] : '';
      const password = passwordMatch ? passwordMatch[1] : '';
      return `const result = await login('${email}', '${password}'); // TODO: Implement login`;
    }

    // "the password is validated"
    if (when.includes('validated')) {
      return `const result = validatePassword(params.password);`;
    }

    return ''; // No action needed
  }

  /**
   * Translate natural language Then to assertion code
   */
  private translateThen(then: string): string {
    // "returns a valid JWT token"
    if (then.includes('returns') && then.includes('JWT')) {
      return `expect(result.token).toBeDefined();`;
    }

    // "returns 401 Unauthorized"
    if (then.includes('401')) {
      return `expect(result.status).toBe(401);`;
    }

    // "error message is X"
    if (then.includes('error message')) {
      const msgMatch = then.match(/"([^"]+)"/);
      const msg = msgMatch ? msgMatch[1] : '';
      return `expect(result.error).toBe('${msg}');`;
    }

    // "token expires in N hours"
    if (then.includes('token expires')) {
      const hoursMatch = then.match(/(\d+) hours/);
      const hours = hoursMatch ? hoursMatch[1] : '24';
      return `expect(result.expiresIn).toBe(${hours} * 60 * 60);`;
    }

    // "account is locked for N minutes"
    if (then.includes('account is locked')) {
      const minutesMatch = then.match(/(\d+) minutes/);
      const minutes = minutesMatch ? minutesMatch[1] : '15';
      return `expect(result.lockedUntil).toBeDefined(); // Locked for ${minutes} minutes`;
    }

    // "validation result is correct"
    if (then.includes('validation result')) {
      return `expect(result).toBe(params.is_valid);`;
    }

    return ''; // No assertion needed
  }

  /**
   * Format a value for TypeScript code
   */
  private formatValue(value: string): string {
    if (value === 'true' || value === 'false') {
      return value;
    }
    if (/^\d+$/.test(value)) {
      return value;
    }
    return `'${value}'`;
  }

  /**
   * Format spec for describe block - use short name if available
   */
  private formatDescribe(spec: TestSpec): string {
    // Use short name if available, otherwise format from id
    if (spec.short) {
      return spec.short;
    }
    return spec.id.replace(/^@tests\//, '').replace(/[-._]/g, ' ');
  }

  /**
   * Get target module name from spec reference
   */
  getTargetModule(target: string): string {
    const parts = target.split('#');
    const name = parts[0].split('/').pop() || 'target';
    return name.charAt(0).toUpperCase() + name.slice(1);
  }

  /**
   * Get target path from spec reference
   */
  getTargetPath(target: string): string {
    return `./${target.split('#')[0].replace('@', '').replace(/\//g, '-')}`;
  }

  /**
   * Generate Python test code
   */
  private generatePython(spec: TestSpec): string {
    const lines: string[] = [];

    lines.push(`# @speclang-generated from ${spec.id}`);
    lines.push(`# @speclang-target ${spec.target}`);
    lines.push('');
    lines.push(`import pytest`);
    lines.push('');
    lines.push(`class Test${this.formatClassName(spec)}:`);

    for (const scenario of spec.scenarios) {
      if (scenario.examples) {
        lines.push(this.generatePythonParameterizedTest(scenario));
      } else {
        lines.push(this.generatePythonStandardTest(scenario));
      }
    }

    return lines.join('\n');
  }

  private generatePythonStandardTest(scenario: TestScenario): string {
    const lines: string[] = [];
    const testName = scenario.name.toLowerCase().replace(/[^a-z0-9]/g, '_');

    lines.push(`    def test_${testName}(self):`);
    lines.push(`        # Given: ${scenario.given.join(', ')}`);
    lines.push(`        # When: ${scenario.when}`);
    for (const then of scenario.then) {
      lines.push(`        # Then: ${then}`);
    }
    lines.push(`        pass`);

    return lines.join('\n');
  }

  private generatePythonParameterizedTest(scenario: TestScenario): string {
    const lines: string[] = [];
    const testName = scenario.name.toLowerCase().replace(/[^a-z0-9]/g, '_');

    lines.push(`    @pytest.mark.parametrize(${JSON.stringify(scenario.examples!.headers)}, ${JSON.stringify(scenario.examples!.rows)})`);
    lines.push(`    def test_${testName}(self, ${scenario.examples!.headers.join(', ')}):`);
    for (const then of scenario.then) {
      lines.push(`        # Then: ${then}`);
    }
    lines.push(`        pass`);

    return lines.join('\n');
  }

  private formatClassName(spec: TestSpec): string {
    // Use short name if available, otherwise format from id
    if (spec.short) {
      return spec.short.replace(/[-_\s]/g, '')
        .split(/[-_\s]/)
        .map(part => part.charAt(0).toUpperCase() + part.slice(1))
        .join('');
    }
    const name = spec.id.replace(/^@tests\//, '').split(/[-._]/)
      .map(part => part.charAt(0).toUpperCase() + part.slice(1))
      .join('');
    return name || 'Test';
  }

  /**
   * Generate Go test code
   */
  private generateGo(spec: TestSpec): string {
    const lines: string[] = [];

    lines.push(`// @speclang-generated from ${spec.id}`);
    lines.push(`// @speclang-target ${spec.target}`);
    lines.push('');
    lines.push(`package main`);
    lines.push('');
    lines.push(`import "testing"`);
    lines.push('');
    lines.push(`func Test${this.formatClassName(spec)}(t *testing.T) {`);

    for (const scenario of spec.scenarios) {
      lines.push(this.generateGoTest(scenario));
    }

    lines.push(`}`);

    return lines.join('\n');
  }

  private generateGoTest(scenario: TestScenario): string {
    const lines: string[] = [];
    const testName = scenario.name.replace(/[^a-zA-Z0-9]/g, '');

    lines.push(`\tt.Run("${scenario.name}", func(t *testing.T) {`);
    lines.push(`\t\t// Given: ${scenario.given.join(', ')}`);
    lines.push(`\t\t// When: ${scenario.when}`);
    for (const then of scenario.then) {
      lines.push(`\t\t// Then: ${then}`);
    }
    lines.push(`\t})`);

    return lines.join('\n');
  }
}

/**
 * Generate test code from a test spec file
 */
export async function generateTestCode(
  specPath: string,
  language: SupportedLanguage = 'typescript'
): Promise<string> {
  const { parseTestSpecFile } = await import('./parser.js');
  const spec = await parseTestSpecFile(specPath);
  const generator = new TestGenerator();
  return generator.generate(spec, language);
}
