"use strict";
// SPECLANG-GENERATED: This file was generated by the speclang-code-gen agent
// Source: @speclang/test-specs
// DO NOT EDIT MANUALLY
Object.defineProperty(exports, "__esModule", { value: true });
exports.updateAllSpecs = exports.syncResultsToSpec = exports.testResultSync = exports.TestResultSync = exports.formatSummary = exports.formatReport = exports.defaultReporter = exports.TestSpecReporter = exports.runAllTestSpecs = exports.runTestSpec = exports.TestRunner = exports.generateTestCode = exports.TestGenerator = exports.parseTestSpecFile = exports.TestSpecParser = void 0;
// Parser
var parser_1 = require("./parser");
Object.defineProperty(exports, "TestSpecParser", { enumerable: true, get: function () { return parser_1.TestSpecParser; } });
Object.defineProperty(exports, "parseTestSpecFile", { enumerable: true, get: function () { return parser_1.parseTestSpecFile; } });
// Generator
var generator_1 = require("./generator");
Object.defineProperty(exports, "TestGenerator", { enumerable: true, get: function () { return generator_1.TestGenerator; } });
Object.defineProperty(exports, "generateTestCode", { enumerable: true, get: function () { return generator_1.generateTestCode; } });
// Runner
var runner_1 = require("./runner");
Object.defineProperty(exports, "TestRunner", { enumerable: true, get: function () { return runner_1.TestRunner; } });
Object.defineProperty(exports, "runTestSpec", { enumerable: true, get: function () { return runner_1.runTestSpec; } });
Object.defineProperty(exports, "runAllTestSpecs", { enumerable: true, get: function () { return runner_1.runAllTestSpecs; } });
// Reporter
var reporter_1 = require("./reporter");
Object.defineProperty(exports, "TestSpecReporter", { enumerable: true, get: function () { return reporter_1.TestSpecReporter; } });
Object.defineProperty(exports, "defaultReporter", { enumerable: true, get: function () { return reporter_1.defaultReporter; } });
Object.defineProperty(exports, "formatReport", { enumerable: true, get: function () { return reporter_1.formatReport; } });
Object.defineProperty(exports, "formatSummary", { enumerable: true, get: function () { return reporter_1.formatSummary; } });
// Sync
var sync_1 = require("./sync");
Object.defineProperty(exports, "TestResultSync", { enumerable: true, get: function () { return sync_1.TestResultSync; } });
Object.defineProperty(exports, "testResultSync", { enumerable: true, get: function () { return sync_1.testResultSync; } });
Object.defineProperty(exports, "syncResultsToSpec", { enumerable: true, get: function () { return sync_1.syncResultsToSpec; } });
Object.defineProperty(exports, "updateAllSpecs", { enumerable: true, get: function () { return sync_1.updateAllSpecs; } });
//# sourceMappingURL=index.js.map