"use strict";
// SPECLANG-GENERATED: This file was generated by the speclang-code-gen agent
// Source: @speclang/test-specs/parser
// DO NOT EDIT MANUALLY
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.TestSpecParser = void 0;
exports.parseTestSpecFile = parseTestSpecFile;
// speclang-header lines:12
// id: @speclang/test-specs/parser
// version: 0.1.0
// layer: 1
// tags: [tests, bdd, parser]
// imports: [@speclang/core]
// status: draft
// short: Test Spec Parser
// @ref: @speclang/test-specs
// @ref: @speclang/test-specs/format
// ---
const yaml = __importStar(require("yaml"));
/**
 * TestSpecParser parses test specs written in natural language
 * and converts them to structured TestSpec objects.
 */
class TestSpecParser {
    /**
     * Parse a test spec content string into a TestSpec object
     */
    parse(content) {
        const header = this.parseHeader(content);
        const scenarios = this.parseScenarios(content);
        return {
            id: header.id,
            version: header.version,
            target: header.target || '',
            scenarios,
            tags: header.tags || [],
            short: header.short
        };
    }
    /**
     * Parse YAML header from test spec content
     * Supports both standard YAML header and speclang header format
     */
    parseHeader(content) {
        // Try standard YAML header first (--- ... ---)
        let headerMatch = content.match(/^---\n([\s\S]*?)\n---/);
        // If not found, try speclang header format (# speclang-header lines:N ... --- YAML ---)
        // This matches: # speclang-header lines:N\n<YAML content>\n---
        if (!headerMatch) {
            headerMatch = content.match(/# speclang-header[^\n]*\n([\s\S]*?)---/);
        }
        if (!headerMatch) {
            throw new Error('No YAML header found in test spec');
        }
        const parsed = yaml.parse(headerMatch[1]);
        if (!parsed || !parsed.id) {
            throw new Error('Test spec must have an id in header');
        }
        return {
            id: parsed.id,
            version: parsed.version || '1.0.0',
            target: parsed.target,
            layer: parsed.layer,
            tags: parsed.tags || [],
            short: parsed.short
        };
    }
    /**
     * Parse all scenarios from test spec content
     */
    parseScenarios(content) {
        const scenarios = [];
        // Match scenario blocks
        // Format:
        // ## Scenario: {name}
        // Given: {precondition}
        // When: {action}
        // Then: {expected}
        const scenarioRegex = /##\s+Scenario:\s+(.+?)\n([\s\S]*?)(?=##\s+Scenario:|$)/g;
        let match;
        while ((match = scenarioRegex.exec(content)) !== null) {
            const name = match[1].trim();
            const body = match[2];
            const scenario = {
                name,
                given: this.parseList(body, 'Given'),
                when: this.parseSingle(body, 'When'),
                then: this.parseList(body, 'Then')
            };
            // Check for examples table
            const examples = this.parseExamples(body);
            if (examples) {
                scenario.examples = examples;
            }
            scenarios.push(scenario);
        }
        return scenarios;
    }
    /**
     * Parse a list of items with a given keyword (e.g., Given, Then)
     */
    parseList(body, keyword) {
        const items = [];
        // Match keyword at start of line, capture everything until next keyword or end
        const regex = new RegExp(`^${keyword}:\\s*(.+)$`, 'gm');
        let match;
        while ((match = regex.exec(body)) !== null) {
            items.push(match[1].trim());
        }
        return items;
    }
    /**
     * Parse a single item with a given keyword (e.g., When)
     */
    parseSingle(body, keyword) {
        const regex = new RegExp(`^${keyword}:\\s*(.+)$`, 'm');
        const match = body.match(regex);
        return match ? match[1].trim() : '';
    }
    /**
     * Parse examples table from markdown format
     * | field1 | field2 |
     * |--------|--------|
     * | value1 | value2 |
     */
    parseExamples(body) {
        const tableRegex = /\|(.+)\|\n\|[-|\s]+\|\n((?:\|.+\|\n?)+)/;
        const match = body.match(tableRegex);
        if (!match)
            return null;
        const headers = match[1].split('|').map(h => h.trim()).filter(Boolean);
        const rows = match[2].trim().split('\n').map(row => row.split('|').map(c => c.trim()).filter(Boolean));
        return { headers, rows };
    }
}
exports.TestSpecParser = TestSpecParser;
/**
 * Parse a test spec from a file
 */
async function parseTestSpecFile(filepath) {
    const fs = await Promise.resolve().then(() => __importStar(require('fs/promises')));
    const content = await fs.readFile(filepath, 'utf-8');
    const parser = new TestSpecParser();
    return parser.parse(content);
}
//# sourceMappingURL=parser.js.map