"use strict";
// SPECLANG-GENERATED: This file was generated by the speclang-code-gen agent
// Source: @speclang/test-specs/reporter
// DO NOT EDIT MANUALLY
Object.defineProperty(exports, "__esModule", { value: true });
exports.defaultReporter = exports.TestSpecReporter = void 0;
exports.formatReport = formatReport;
exports.formatSummary = formatSummary;
/**
 * TestSpecReporter formats test results for display
 */
class TestSpecReporter {
    /**
     * Format a single test report as a readable string
     */
    formatReport(report) {
        const lines = [];
        lines.push(`Test Report: ${report.specId}`);
        lines.push('─'.repeat(40));
        lines.push(`Scenarios: ${report.totalScenarios}`);
        lines.push(`  ✓ Passed: ${report.passed}`);
        lines.push(`  ✗ Failed: ${report.failed}`);
        lines.push(`  ○ Skipped: ${report.skipped}`);
        lines.push(`Duration: ${report.duration}ms`);
        lines.push('');
        for (const result of report.results) {
            const icon = result.status === 'passed' ? '✓' :
                result.status === 'failed' ? '✗' : '○';
            lines.push(`  ${icon} ${result.scenarioName} (${result.duration}ms)`);
            if (result.error) {
                lines.push(`    Error: ${this.truncateError(result.error)}`);
            }
        }
        return lines.join('\n');
    }
    /**
     * Format multiple test reports as a summary
     */
    formatSummary(reports) {
        const totals = reports.reduce((acc, r) => ({
            total: acc.total + r.totalScenarios,
            passed: acc.passed + r.passed,
            failed: acc.failed + r.failed,
            skipped: acc.skipped + r.skipped,
            duration: acc.duration + r.duration
        }), { total: 0, passed: 0, failed: 0, skipped: 0, duration: 0 });
        const passRate = totals.total > 0
            ? ((totals.passed / totals.total) * 100).toFixed(1)
            : '0.0';
        return `
Test Summary
═══════════════════════════════════════
Specs: ${reports.length}
Scenarios: ${totals.total}
  ✓ Passed: ${totals.passed}
  ✗ Failed: ${totals.failed}
  ○ Skipped: ${totals.skipped}
Pass Rate: ${passRate}%
Duration: ${totals.duration}ms
`.trim();
    }
    /**
     * Format a test result as JSON
     */
    formatJson(report) {
        return JSON.stringify(report, null, 2);
    }
    /**
     * Format reports as JSON array
     */
    formatJsonAll(reports) {
        return JSON.stringify(reports, null, 2);
    }
    /**
     * Format a compact single-line summary
     */
    formatCompact(report) {
        const status = report.failed > 0 ? '✗' : report.skipped > 0 ? '○' : '✓';
        return `${status} ${report.specId}: ${report.passed}/${report.totalScenarios} passed (${report.duration}ms)`;
    }
    /**
     * Format failures only
     */
    formatFailures(reports) {
        const lines = ['Failed Tests', '─'.repeat(40)];
        for (const report of reports) {
            const failures = report.results.filter(r => r.status === 'failed');
            if (failures.length > 0) {
                lines.push(`\n${report.specId}:`);
                for (const failure of failures) {
                    lines.push(`  ✗ ${failure.scenarioName}`);
                    if (failure.error) {
                        lines.push(`    ${this.truncateError(failure.error, 100)}`);
                    }
                }
            }
        }
        return lines.join('\n');
    }
    /**
     * Get summary statistics
     */
    getSummaryStats(reports) {
        const totals = reports.reduce((acc, r) => ({
            specs: acc.specs + 1,
            scenarios: acc.scenarios + r.totalScenarios,
            passed: acc.passed + r.passed,
            failed: acc.failed + r.failed,
            skipped: acc.skipped + r.skipped,
            duration: acc.duration + r.duration
        }), { specs: 0, scenarios: 0, passed: 0, failed: 0, skipped: 0, duration: 0 });
        return {
            totalSpecs: totals.specs,
            totalScenarios: totals.scenarios,
            totalPassed: totals.passed,
            totalFailed: totals.failed,
            totalSkipped: totals.skipped,
            totalDuration: totals.duration,
            passRate: totals.scenarios > 0
                ? (totals.passed / totals.scenarios) * 100
                : 0
        };
    }
    /**
     * Truncate error message to a reasonable length
     */
    truncateError(error, maxLength = 200) {
        if (error.length <= maxLength)
            return error;
        return error.substring(0, maxLength) + '...';
    }
}
exports.TestSpecReporter = TestSpecReporter;
/**
 * Create a default reporter instance
 */
exports.defaultReporter = new TestSpecReporter();
/**
 * Format a test report using default reporter
 */
function formatReport(report) {
    return exports.defaultReporter.formatReport(report);
}
/**
 * Format test summary using default reporter
 */
function formatSummary(reports) {
    return exports.defaultReporter.formatSummary(reports);
}
//# sourceMappingURL=reporter.js.map