"use strict";
// SPECLANG-GENERATED: This file was generated by the speclang-code-gen agent
// Source: @speclang/test-specs/runner
// DO NOT EDIT MANUALLY
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.TestRunner = void 0;
exports.runTestSpec = runTestSpec;
exports.runAllTestSpecs = runAllTestSpecs;
// speclang-header lines:12
// id: @speclang/test-specs/runner
// version: 0.1.0
// layer: 1
// tags: [tests, bdd, runner]
// imports: [@speclang/core]
// status: draft
// short: Test Runner
// @ref: @speclang/test-specs
// ---
const fs = __importStar(require("fs/promises"));
const path = __importStar(require("path"));
const glob_1 = require("glob");
const parser_1 = require("./parser");
const generator_1 = require("./generator");
/**
 * TestRunner executes test specs and collects results
 */
class TestRunner {
    language;
    constructor(language = 'typescript') {
        this.language = language;
    }
    /**
     * Run a single test spec file
     */
    async runTestSpec(specPath) {
        const parser = new parser_1.TestSpecParser();
        const content = await fs.readFile(specPath, 'utf-8');
        const testSpec = parser.parse(content);
        // Generate test file
        const generator = new generator_1.TestGenerator();
        const testCode = generator.generate(testSpec, this.language);
        // Write to temp file
        const testPath = specPath.replace('.test.spec.md', '.generated.test.ts');
        await fs.writeFile(testPath, testCode);
        // Run tests
        const results = await this.executeTests(testPath);
        return {
            specId: testSpec.id,
            totalScenarios: testSpec.scenarios.length,
            passed: results.filter(r => r.status === 'passed').length,
            failed: results.filter(r => r.status === 'failed').length,
            skipped: results.filter(r => r.status === 'skipped').length,
            duration: results.reduce((sum, r) => sum + r.duration, 0),
            results
        };
    }
    /**
     * Execute tests and parse results
     */
    async executeTests(testPath) {
        const results = [];
        try {
            // Run bun test and capture JSON output
            const { exec } = await Promise.resolve().then(() => __importStar(require('child_process')));
            const { promisify } = await Promise.resolve().then(() => __importStar(require('util')));
            const execAsync = promisify(exec);
            try {
                const { stdout } = await execAsync(`bun test ${testPath} --reporter=json 2>&1`, {
                    timeout: 30000
                });
                // Parse JSON output
                const testOutput = JSON.parse(stdout);
                for (const test of testOutput.tests || []) {
                    results.push({
                        specId: testPath,
                        scenarioName: test.name,
                        status: test.status,
                        duration: test.duration || 0,
                        error: test.error?.message || test.error,
                        timestamp: Date.now()
                    });
                }
            }
            catch (execError) {
                // If tests fail to run, create a failed result
                results.push({
                    specId: testPath,
                    scenarioName: 'test execution',
                    status: 'failed',
                    duration: 0,
                    error: execError.message || 'Failed to execute tests',
                    timestamp: Date.now()
                });
            }
        }
        catch (error) {
            results.push({
                specId: testPath,
                scenarioName: 'unknown',
                status: 'failed',
                duration: 0,
                error: error.message || 'Unknown error',
                timestamp: Date.now()
            });
        }
        return results;
    }
    /**
     * Run all test specs in a directory
     */
    async runAllTestSpecs(dir) {
        const files = await this.findTestSpecs(dir);
        const reports = [];
        for (const file of files) {
            try {
                const report = await this.runTestSpec(file);
                reports.push(report);
            }
            catch (error) {
                // Create a failure report for specs that couldn't run
                reports.push({
                    specId: file,
                    totalScenarios: 0,
                    passed: 0,
                    failed: 0,
                    skipped: 0,
                    duration: 0,
                    results: [{
                            specId: file,
                            scenarioName: 'spec parsing',
                            status: 'failed',
                            duration: 0,
                            error: error.message,
                            timestamp: Date.now()
                        }]
                });
            }
        }
        return reports;
    }
    /**
     * Find all test spec files in a directory
     */
    async findTestSpecs(dir) {
        const pattern = path.join(dir, '**/*.test.spec.md');
        return (0, glob_1.glob)(pattern, { absolute: true });
    }
    /**
     * Generate test code without running
     */
    async generateOnly(specPath, outputPath) {
        const parser = new parser_1.TestSpecParser();
        const content = await fs.readFile(specPath, 'utf-8');
        const testSpec = parser.parse(content);
        const generator = new generator_1.TestGenerator();
        const testCode = generator.generate(testSpec, this.language);
        if (outputPath) {
            await fs.writeFile(outputPath, testCode);
        }
        return testCode;
    }
}
exports.TestRunner = TestRunner;
/**
 * Run a test spec and return results
 */
async function runTestSpec(specPath, language = 'typescript') {
    const runner = new TestRunner(language);
    return runner.runTestSpec(specPath);
}
/**
 * Run all test specs in a directory
 */
async function runAllTestSpecs(dir, language = 'typescript') {
    const runner = new TestRunner(language);
    return runner.runAllTestSpecs(dir);
}
//# sourceMappingURL=runner.js.map