"use strict";
// SPECLANG-GENERATED: This file was generated by the speclang-code-gen agent
// Source: @speclang/test-specs/sync
// DO NOT EDIT MANUALLY
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.testResultSync = exports.TestResultSync = void 0;
exports.syncResultsToSpec = syncResultsToSpec;
exports.updateAllSpecs = updateAllSpecs;
// speclang-header lines:12
// id: @speclang/test-specs/sync
// version: 0.1.0
// layer: 1
// tags: [tests, bdd, sync]
// imports: [@speclang/core]
// status: draft
// short: Test Result Sync
// @ref: @speclang/test-specs
// ---
const fs = __importStar(require("fs/promises"));
const path = __importStar(require("path"));
const glob_1 = require("glob");
/**
 * TestResultSync synchronizes test results back to test spec files
 */
class TestResultSync {
    /**
     * Sync test results to a specific test spec file
     */
    async syncResultsToSpec(specPath, report) {
        let content = await fs.readFile(specPath, 'utf-8');
        // Add result markers to each scenario
        for (const result of report.results) {
            const scenarioMarker = `## Scenario: ${result.scenarioName}`;
            // Check if scenario exists in the file
            if (content.includes(scenarioMarker)) {
                const statusMarker = `\n<!-- @test-status: ${result.status} (${result.duration}ms) -->`;
                // Replace the scenario header with header + status
                content = content.replace(scenarioMarker, scenarioMarker + statusMarker);
            }
        }
        // Add summary at end
        const summary = `
---

<!-- @test-report
passed: ${report.passed}
failed: ${report.failed}
skipped: ${report.skipped}
duration: ${report.duration}ms
timestamp: ${new Date().toISOString()}
-->
`;
        // Check if there's already a test-report comment
        if (content.includes('<!-- @test-report')) {
            // Replace existing summary
            const existingReportRegex = /<!-- @test-report[\s\S]*?-->/;
            content = content.replace(existingReportRegex, summary.trim());
        }
        else {
            content += summary;
        }
        await fs.writeFile(specPath, content);
    }
    /**
     * Update all test specs in a directory with their results
     */
    async updateAllSpecs(dir, reports) {
        for (const report of reports) {
            const specPath = await this.findSpecForReport(report);
            if (specPath) {
                await this.syncResultsToSpec(specPath, report);
            }
        }
    }
    /**
     * Find the spec file for a given report
     */
    async findSpecForReport(report) {
        // Try to find the spec file based on the specId
        const pattern = `**/${report.specId.replace('@tests/', '')}*.test.spec.md`;
        const files = await (0, glob_1.glob)(pattern, { absolute: true });
        if (files.length > 0) {
            return files[0];
        }
        // Fallback: try to find by specId in content
        const allFiles = await (0, glob_1.glob)('**/*.test.spec.md', { absolute: true });
        for (const file of allFiles) {
            try {
                const content = await fs.readFile(file, 'utf-8');
                if (content.includes(`id: "${report.specId}"`) ||
                    content.includes(`id: '${report.specId}'`)) {
                    return file;
                }
            }
            catch {
                // Skip files that can't be read
            }
        }
        return null;
    }
    /**
     * Clear all test results from a spec file
     */
    async clearResults(specPath) {
        let content = await fs.readFile(specPath, 'utf-8');
        // Remove status markers
        content = content.replace(/\n<!-- @test-status: .*? -->/g, '');
        // Remove test report comment
        content = content.replace(/\n---\n\n<!-- @test-report[\s\S]*?-->/g, '');
        await fs.writeFile(specPath, content);
    }
    /**
     * Clear all test results from all specs in a directory
     */
    async clearAllResults(dir) {
        const files = await (0, glob_1.glob)(path.join(dir, '**/*.test.spec.md'));
        for (const file of files) {
            await this.clearResults(file);
        }
    }
    /**
     * Read test results from a spec file
     */
    async readResults(specPath) {
        const content = await fs.readFile(specPath, 'utf-8');
        // Extract status for each scenario
        const statusRegex = /@test-status: (\w+) \((\d+)ms\)/g;
        const statuses = [];
        let match;
        while ((match = statusRegex.exec(content)) !== null) {
            statuses.push({
                scenario: '',
                status: match[1],
                duration: parseInt(match[2])
            });
        }
        // Extract summary
        const summaryMatch = content.match(/<!-- @test-report([\s\S]*?)-->/);
        if (!summaryMatch) {
            return statuses.length > 0 ? { status: 'partial' } : null;
        }
        const summaryContent = summaryMatch[1];
        const passedMatch = summaryContent.match(/passed:\s*(\d+)/);
        const failedMatch = summaryContent.match(/failed:\s*(\d+)/);
        const skippedMatch = summaryContent.match(/skipped:\s*(\d+)/);
        const durationMatch = summaryContent.match(/duration:\s*(\d+)/);
        const timestampMatch = summaryContent.match(/timestamp:\s*(.+)/);
        return {
            status: 'complete',
            passed: passedMatch ? parseInt(passedMatch[1]) : undefined,
            failed: failedMatch ? parseInt(failedMatch[1]) : undefined,
            skipped: skippedMatch ? parseInt(skippedMatch[1]) : undefined,
            duration: durationMatch ? parseInt(durationMatch[1]) : undefined,
            timestamp: timestampMatch ? timestampMatch[1].trim() : undefined
        };
    }
}
exports.TestResultSync = TestResultSync;
/**
 * Create a default sync instance
 */
exports.testResultSync = new TestResultSync();
/**
 * Sync results to a spec file
 */
async function syncResultsToSpec(specPath, report) {
    return exports.testResultSync.syncResultsToSpec(specPath, report);
}
/**
 * Update all specs in a directory
 */
async function updateAllSpecs(dir, reports) {
    return exports.testResultSync.updateAllSpecs(dir, reports);
}
//# sourceMappingURL=sync.js.map