"use strict";
// SPECLANG-GENERATED: This file was generated by the speclang-code-gen agent
// Source: @speclang/test-specs
// DO NOT EDIT MANUALLY
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=types.js.map