/**
speclang-header lines:5
id: @specs/test-specs
version: 1.0.0
layer: 5
 */

// SPECLANG-GENERATED: This file was generated by the speclang-code-gen agent
// Source: @speclang/test-specs
// DO NOT EDIT MANUALLY

// speclang-header lines:12
// id: @speclang/test-specs/types
// version: 0.1.0
// layer: 1
// tags: [tests, bdd, types]
// imports: [@speclang/core]
// status: draft
// short: Test Spec Types
// @ref: @speclang/test-specs
// ---

/**
 * TypeScript types for Test Specs
 * Test specs are first-class citizens that describe expected behavior
 * and are converted to executable tests by the TestWriter agent.
 */

export interface TestSpec {
  id: string;
  version: string;
  target: string;
  scenarios: TestScenario[];
  tags: string[];
  short?: string;
}

export interface TestScenario {
  name: string;
  given: string[];
  when: string;
  then: string[];
  examples?: ExampleTable;
}

export interface ExampleTable {
  headers: string[];
  rows: string[][];
}

export interface TestResult {
  specId: string;
  scenarioName: string;
  status: 'passed' | 'failed' | 'skipped';
  duration: number;
  error?: string;
  timestamp: number;
}

export interface TestReport {
  specId: string;
  totalScenarios: number;
  passed: number;
  failed: number;
  skipped: number;
  duration: number;
  results: TestResult[];
}

export type SupportedLanguage = 'typescript' | 'python' | 'go';

export interface TestSpecHeader {
  id: string;
  version: string;
  target?: string;
  layer?: number;
  tags?: string[];
  short?: string;
}
