/**
 * SPECLANG-GENERATED: Go code templates
 * Source: @speclang/compiler.spec.dir/go
 */

export const GO_TEMPLATES = {
  fileHeader: `// Code generated by SpecLang. DO NOT EDIT.
// Source: {{source}}
// Generated: {{timestamp}}

package {{package}}
`,

  struct: `type {{name}} struct {
{{fields}}
}
`,

  field: `{{name}} {{type}} {{tag}}`,

  jsonTag: '`json:"{{name}}{{omitempty}}"`',

  interface: `type {{name}} interface {
{{methods}}
}
`,

  interfaceMethod: `{{name}}({{params}}) ({{returns}})`,

  function: `func {{receiver}}{{name}}({{params}}) ({{returns}}) {
{{body}}
}`,

  receiver: `(r *{{type}}) `,

  constructor: `func New{{name}}({{params}}) *{{name}} {
    return &{{name}}{
{{fieldInits}}
    }
}
`,

  errorType: `type {{name}}Error struct {
    Code    string
    Message string
    Cause   error
}

func (e *{{name}}Error) Error() string {
    return fmt.Sprintf("{{name}} error: %s: %s", e.Code, e.Message)
}

func (e *{{name}}Error) Unwrap() error {
    return e.Cause
}
`,

  enum: `type {{name}} int

const (
    {{firstValue}} {{name}} = iota
{{otherValues}}
)
`,

  httpHandler: `func (h *{{handler}}) {{method}}(w http.ResponseWriter, r *http.Request) {
{{body}}
}`,

  importBlock: `import (
{{imports}}
)`,

  importSingle: `import "{{package}}"`,

  fieldInit: `{{name}}: {{value}},`,
};

export function renderGoTemplate(
  template: string,
  vars: Record<string, string>
): string {
  let result = template;
  for (const [key, value] of Object.entries(vars)) {
    result = result.replace(new RegExp(`{{${key}}}`, 'g'), value);
  }
  return result;
}

// ---- Type definitions ----

export interface GoFieldDef {
  name: string;
  type: string;
  tag?: string;
}

export interface GoMethodDef {
  name: string;
  params: string;
  returns: string;
}

// ---- Renderers ----

export function renderStruct(name: string, fields: GoFieldDef[]): string {
  const fieldLines = fields.map(f => {
    const parts = [`\t${f.name} ${f.type}`];
    if (f.tag) parts.push(f.tag);
    return parts.join(' ');
  });
  return renderGoTemplate(GO_TEMPLATES.struct, {
    name,
    fields: fieldLines.join('\n'),
  });
}

export function renderInterface(name: string, methods: GoMethodDef[]): string {
  const methodLines = methods.map(m =>
    renderGoTemplate(GO_TEMPLATES.interfaceMethod, {
      name: m.name,
      params: m.params,
      returns: m.returns,
    })
  );
  return renderGoTemplate(GO_TEMPLATES.interface, {
    name,
    methods: methodLines.join('\n'),
  });
}

export function renderConstructor(
  name: string,
  fields: GoFieldDef[]
): string {
  const params = fields.map(f => `${toCamelCase(f.name)} ${f.type}`).join(', ');
  const fieldInits = fields
    .map(f => `    ${f.name}: ${toCamelCase(f.name)},`)
    .join('\n');
  return renderGoTemplate(GO_TEMPLATES.constructor, {
    name,
    params,
    fieldInits,
  });
}

export function renderImports(packages: string[]): string {
  if (packages.length === 0) return '';
  if (packages.length === 1) {
    return renderGoTemplate(GO_TEMPLATES.importSingle, {
      package: packages[0],
    });
  }
  const lines = packages.map(p => `\t"${p}"`).join('\n');
  return renderGoTemplate(GO_TEMPLATES.importBlock, { imports: lines });
}

export function renderFile(
  pkg: string,
  imports: string | string[],
  body: string,
  source: string
): string {
  const timestamp = new Date().toISOString();
  const header = renderGoTemplate(GO_TEMPLATES.fileHeader, {
    source,
    timestamp,
    package: pkg,
  });
  const impBlock = typeof imports === 'string' ? imports : renderImports(imports);
  return [header, impBlock, body].filter(Boolean).join('\n\n');
}

// ---- Naming utilities ----

const GO_INITIALISMS = new Set([
  'id', 'url', 'http', 'https', 'json', 'xml', 'api', 'sql', 'uuid',
  'tcp', 'udp', 'ip', 'dns', 'ssh', 'tls', 'ssl', 'os', 'db', 'io',
  'ui', 'ok', 'rpc', 'gql', 'orm',
]);

function splitWords(name: string): string[] {
  return name
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .split(/[_\-\s]+/)
    .filter(Boolean);
}

export function toPascalCase(name: string): string {
  return splitWords(name)
    .map(part => {
      const lower = part.toLowerCase();
      if (GO_INITIALISMS.has(lower)) return lower.toUpperCase();
      return part.charAt(0).toUpperCase() + part.slice(1);
    })
    .join('');
}

export function toCamelCase(name: string): string {
  const words = splitWords(name);
  return words
    .map((part, i) => {
      if (i === 0) return part.toLowerCase();
      const lower = part.toLowerCase();
      if (GO_INITIALISMS.has(lower)) return lower.toUpperCase();
      return part.charAt(0).toUpperCase() + part.slice(1);
    })
    .join('');
}

export function toSnakeCase(name: string): string {
  return name
    .replace(/([A-Z])/g, '_$1')
    .replace(/[_\-\s]+/g, '_')
    .toLowerCase()
    .replace(/^_/, '');
}
// test write Sat Jun 13 15:41:42 UTC 2026
