/**
 * SPECLANG-GENERATED: Go code templates
 * Source: @speclang/compiler.spec.dir/go
 */

export const GO_TEMPLATES = {
  fileHeader: `// Code generated by SpecLang. DO NOT EDIT.
// Source: {{source}}
// Generated: {{timestamp}}

package {{package}}
`,

  struct: `type {{name}} struct {
{{fields}}
}
`,

  field: `{{name}} {{type}} {{tag}}`,

  jsonTag: '`json:"{{name}}{{omitempty}}"`',

  interface: `type {{name}} interface {
{{methods}}
}
`,

  interfaceMethod: `{{name}}({{params}}) ({{returns}})`,

  function: `func {{receiver}}{{name}}({{params}}) ({{returns}}) {
{{body}}
}`,

  receiver: `(r *{{type}}) `,

  constructor: `func New{{name}}({{params}}) *{{name}} {
    return &{{name}}{
{{fieldInits}}
    }
}
`,

  errorType: `type {{name}}Error struct {
    Code    string
    Message string
    Cause   error
}

func (e *{{name}}Error) Error() string {
    return fmt.Sprintf("{{name}} error: %s: %s", e.Code, e.Message)
}

func (e *{{name}}Error) Unwrap() error {
    return e.Cause
}
`,

  enum: `type {{name}} int

const (
    {{firstValue}} {{name}} = iota
{{otherValues}}
)
`,

  httpHandler: `func (h *{{handler}}) {{method}}(w http.ResponseWriter, r *http.Request) {
{{body}}
}`,

  importBlock: `import (
{{imports}}
)`,

  importSingle: `import "{{package}}"`,

  fieldInit: `{{name}}: {{value}},`,
};

export function renderGoTemplate(
  template: string,
  vars: Record<string, string>
): string {
  let result = template;
  for (const [key, value] of Object.entries(vars)) {
    result = result.replace(new RegExp(`{{${key}}}`, 'g'), value);
  }
  return result;
}
