"use strict";
/**
 * SPECLANG-GENERATED: Go code templates
 * Source: @speclang/compiler.spec.dir/go
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GO_TEMPLATES = void 0;
exports.renderGoTemplate = renderGoTemplate;
exports.toPascalCase = toPascalCase;
exports.toCamelCase = toCamelCase;
exports.toSnakeCase = toSnakeCase;
exports.renderStruct = renderStruct;
exports.renderInterface = renderInterface;
exports.renderConstructor = renderConstructor;
exports.renderImports = renderImports;
exports.renderFile = renderFile;
exports.GO_TEMPLATES = {
    fileHeader: `// Code generated by SpecLang. DO NOT EDIT.
// Source: {{source}}
// Generated: {{timestamp}}

package {{package}}
`,
    struct: `type {{name}} struct {
{{fields}}
}
`,
    field: `{{name}} {{type}} {{tag}}`,
    jsonTag: '`json:"{{name}}{{omitempty}}"`',
    interface: `type {{name}} interface {
{{methods}}
}
`,
    interfaceMethod: `{{name}}({{params}}) ({{returns}})`,
    function: `func {{receiver}}{{name}}({{params}}) ({{returns}}) {
{{body}}
}`,
    receiver: `(r *{{type}}) `,
    constructor: `func New{{name}}({{params}}) *{{name}} {
    return &{{name}}{
{{fieldInits}}
    }
}
`,
    errorType: `type {{name}}Error struct {
    Code    string
    Message string
    Cause   error
}

func (e *{{name}}Error) Error() string {
    return fmt.Sprintf("{{name}} error: %s: %s", e.Code, e.Message)
}

func (e *{{name}}Error) Unwrap() error {
    return e.Cause
}
`,
    enum: `type {{name}} int

const (
    {{firstValue}} {{name}} = iota
{{otherValues}}
)
`,
    httpHandler: `func (h *{{handler}}) {{method}}(w http.ResponseWriter, r *http.Request) {
{{body}}
}`,
    importBlock: `import (
{{imports}}
)`,
    importSingle: `import "{{package}}"`,
    fieldInit: `{{name}}: {{value}},`,
};
function renderGoTemplate(template, vars) {
    let result = template;
    for (const [key, value] of Object.entries(vars)) {
        result = result.replace(new RegExp(`{{${key}}}`, 'g'), value);
    }
    return result;
}
function toPascalCase(s) {
    const parts = s
        .split(/[-_\s]+|(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])/)
        .filter(Boolean);
    return parts
        .map((w, _i, arr) => {
        // For single-word input: if ≤2 chars or already uppercase → uppercase all
        if (arr.length === 1 && (w.length <= 2 || w === w.toUpperCase())) {
            return w.toUpperCase();
        }
        // For segments: only preserve existing uppercase (e.g., ID, SKU)
        if (w === w.toUpperCase())
            return w.toUpperCase();
        return w.charAt(0).toUpperCase() + w.slice(1);
    })
        .join('');
}
function toCamelCase(s) {
    const pascal = toPascalCase(s);
    if (pascal.length <= 2 || pascal === pascal.toUpperCase())
        return pascal.toLowerCase();
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}
function toSnakeCase(s) {
    return s
        .replace(/([A-Z])/g, '_$1')
        .toLowerCase()
        .replace(/^_/, '')
        .replace(/__+/g, '_');
}
function renderStruct(name, fields) {
    const renderedFields = fields
        .map(f => renderGoTemplate(exports.GO_TEMPLATES.field, { name: f.name, type: f.type, tag: f.tag }))
        .join('\n');
    return renderGoTemplate(exports.GO_TEMPLATES.struct, { name, fields: renderedFields });
}
function renderInterface(name, methods) {
    const renderedMethods = methods
        .map(m => renderGoTemplate(exports.GO_TEMPLATES.interfaceMethod, { name: m.name, params: m.params, returns: m.returns }))
        .join('\n');
    return renderGoTemplate(exports.GO_TEMPLATES.interface, { name, methods: renderedMethods });
}
function renderConstructor(name, fields) {
    const params = fields
        .map(f => `${f.name.charAt(0).toLowerCase() + f.name.slice(1)} ${f.type}`)
        .join(', ');
    const fieldInits = fields
        .map(f => `    ${f.name}: ${f.name.charAt(0).toLowerCase() + f.name.slice(1)},`)
        .join('\n');
    return renderGoTemplate(exports.GO_TEMPLATES.constructor, {
        name,
        params,
        fieldInits,
    });
}
function renderImports(imports) {
    if (imports.length === 0)
        return '';
    if (imports.length === 1) {
        return renderGoTemplate(exports.GO_TEMPLATES.importSingle, { package: imports[0] });
    }
    const sorted = [...imports].sort();
    const rendered = sorted.map(i => `  "${i}"`).join('\n');
    return renderGoTemplate(exports.GO_TEMPLATES.importBlock, { imports: rendered });
}
function renderFile(pkg, imports, body, source) {
    const now = new Date().toISOString();
    const header = renderGoTemplate(exports.GO_TEMPLATES.fileHeader, {
        source,
        timestamp: now,
        package: pkg,
    });
    const importBlock = renderImports(imports);
    const sep = importBlock ? '\n' : '';
    return header + importBlock + sep + body + '\n';
}
