/**
 * SPECLANG-GENERATED - Do not edit directly
 * 
 * Source: specs/config.dir/schema.spec.md
 * Blocks: @block:config/structure
 * Generated: 2026-02-22
 * 
 * Edit the spec, not this file.
 */

import { readFile } from 'fs/promises';
import { parse } from 'yaml';
import type { ProjectConfig } from './schema.js';
import {
  DEFAULT_WATCHER_CONFIG,
  DEFAULT_SPLIT_CONFIG,
  DEFAULT_EMBEDDING_CONFIG,
  DEFAULT_DATABASE_CONFIG,
  DEFAULT_CASCADE_CONFIG,
} from './schema.js';

/**
 * Load configuration from a YAML file
 */
export async function loadConfig(filePath: string = '.speclangrc'): Promise<ProjectConfig> {
  try {
    const content = await readFile(filePath, 'utf-8');
    const parsed = parse(content);
    return mergeWithDefaults(parsed);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      // File doesn't exist, return default config
      return getDefaultConfig();
    }
    throw error;
  }
}

/**
 * Merge user configuration with defaults
 */
function mergeWithDefaults(userConfig: Partial<ProjectConfig>): ProjectConfig {
  const defaults = getDefaultConfig();
  return {
    metadata: userConfig.metadata ?? defaults.metadata,
    targets: userConfig.targets ?? defaults.targets,
    config: {
      watcher: userConfig.config?.watcher ?? defaults.config.watcher,
      split: userConfig.config?.split ?? defaults.config.split,
      embeddings: userConfig.config?.embeddings ?? defaults.config.embeddings,
      database: userConfig.config?.database ?? defaults.config.database,
      cascade: userConfig.config?.cascade ?? defaults.config.cascade,
      agents: userConfig.config?.agents ?? defaults.config.agents,
    },
  };
}

/**
 * Get default configuration
 */
export function getDefaultConfig(): ProjectConfig {
  return {
    metadata: {
      name: 'Unnamed Project',
      version: '0.1.0',
      description: 'Generated by SpecLang',
    },
    targets: ['typescript'],
    config: {
      watcher: structuredClone(DEFAULT_WATCHER_CONFIG),
      split: structuredClone(DEFAULT_SPLIT_CONFIG),
      embeddings: structuredClone(DEFAULT_EMBEDDING_CONFIG),
      database: structuredClone(DEFAULT_DATABASE_CONFIG),
      cascade: structuredClone(DEFAULT_CASCADE_CONFIG),
      agents: {},
    },
  };
}