"use strict";
/**
 * SPECLANG-GENERATED - Do not edit directly
 *
 * Source: specs/config.dir/schema.spec.md
 * Blocks: @block:config/structure
 * Generated: 2026-02-22
 *
 * Edit the spec, not this file.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.loadConfig = loadConfig;
exports.getDefaultConfig = getDefaultConfig;
const promises_1 = require("fs/promises");
const yaml_1 = require("yaml");
const schema_js_1 = require("./schema.js");
/**
 * Load configuration from a YAML file
 */
async function loadConfig(filePath = '.speclangrc') {
    try {
        const content = await (0, promises_1.readFile)(filePath, 'utf-8');
        const parsed = (0, yaml_1.parse)(content);
        return mergeWithDefaults(parsed);
    }
    catch (error) {
        if (error.code === 'ENOENT') {
            // File doesn't exist, return default config
            return getDefaultConfig();
        }
        throw error;
    }
}
/**
 * Merge user configuration with defaults
 */
function mergeWithDefaults(userConfig) {
    const defaults = getDefaultConfig();
    return {
        metadata: userConfig.metadata ?? defaults.metadata,
        targets: userConfig.targets ?? defaults.targets,
        config: {
            watcher: userConfig.config?.watcher ?? defaults.config.watcher,
            split: userConfig.config?.split ?? defaults.config.split,
            embeddings: userConfig.config?.embeddings ?? defaults.config.embeddings,
            database: userConfig.config?.database ?? defaults.config.database,
            cascade: userConfig.config?.cascade ?? defaults.config.cascade,
            agents: userConfig.config?.agents ?? defaults.config.agents,
        },
    };
}
/**
 * Get default configuration
 */
function getDefaultConfig() {
    return {
        metadata: {
            name: 'Unnamed Project',
            version: '0.1.0',
            description: 'Generated by SpecLang',
        },
        targets: ['typescript'],
        config: {
            watcher: structuredClone(schema_js_1.DEFAULT_WATCHER_CONFIG),
            split: structuredClone(schema_js_1.DEFAULT_SPLIT_CONFIG),
            embeddings: structuredClone(schema_js_1.DEFAULT_EMBEDDING_CONFIG),
            database: structuredClone(schema_js_1.DEFAULT_DATABASE_CONFIG),
            cascade: structuredClone(schema_js_1.DEFAULT_CASCADE_CONFIG),
            agents: {},
        },
    };
}
//# sourceMappingURL=loader.js.map