// SPECLANG-GENERATED: This file was generated by the speclang-code-gen agent
// Source: @speclang/test-specs
// DO NOT EDIT MANUALLY

// speclang-header lines:12
// id: @speclang/test-specs
// version: 0.1.0
// layer: 0
// tags: [tests, bdd, natural-language]
// imports: [@speclang/core]
// status: draft
// short: Test Specs
// @ref: @speclang/test-specs/format
// @ref: @speclang/test-specs/examples
// ---

/**
 * Test Specs Module
 * 
 * Tests written as natural language specifications. First-class citizens.
 * TestWriter agent converts to executable tests.
 */

// Types - using type export since interfaces don't exist at runtime
export type {
  TestSpec,
  TestScenario,
  ExampleTable,
  TestResult,
  TestReport,
  SupportedLanguage,
  TestSpecHeader
} from './types';

// Parser
export { TestSpecParser, parseTestSpecFile } from './parser';

// Generator
export { TestGenerator, generateTestCode } from './generator';

// Runner
export { TestRunner, runTestSpec, runAllTestSpecs } from './runner';

// Reporter
export { 
  TestSpecReporter, 
  defaultReporter, 
  formatReport, 
  formatSummary 
} from './reporter';

// Sync
export { TestResultSync, testResultSync, syncResultsToSpec, updateAllSpecs } from './sync';
