// SPECLANG-GENERATED: This file was generated by the speclang-code-gen agent
// Source: @speclang/test-specs/parser
// DO NOT EDIT MANUALLY

// speclang-header lines:12
// id: @speclang/test-specs/parser
// version: 0.1.0
// layer: 1
// tags: [tests, bdd, parser]
// imports: [@speclang/core]
// status: draft
// short: Test Spec Parser
// @ref: @speclang/test-specs
// @ref: @speclang/test-specs/format
// ---

import * as yaml from 'yaml';
import { TestSpec, TestScenario, ExampleTable, TestSpecHeader } from './types';

/**
 * TestSpecParser parses test specs written in natural language
 * and converts them to structured TestSpec objects.
 */
export class TestSpecParser {
  /**
   * Parse a test spec content string into a TestSpec object
   */
  parse(content: string): TestSpec {
    const header = this.parseHeader(content);
    const scenarios = this.parseScenarios(content);

    return {
      id: header.id,
      version: header.version,
      target: header.target || '',
      scenarios,
      tags: header.tags || [],
      short: header.short
    };
  }

  /**
   * Parse YAML header from test spec content
   * Supports both standard YAML header and speclang header format
   */
  private parseHeader(content: string): TestSpecHeader {
    // Try standard YAML header first (--- ... ---)
    let headerMatch = content.match(/^---\n([\s\S]*?)\n---/);
    
    // If not found, try speclang header format (# speclang-header lines:N ... --- YAML ---)
    // This matches: # speclang-header lines:N\n<YAML content>\n---
    if (!headerMatch) {
      headerMatch = content.match(/# speclang-header[^\n]*\n([\s\S]*?)---/);
    }
    
    if (!headerMatch) {
      throw new Error('No YAML header found in test spec');
    }

    const parsed = yaml.parse(headerMatch[1]);
    if (!parsed || !parsed.id) {
      throw new Error('Test spec must have an id in header');
    }

    return {
      id: parsed.id,
      version: parsed.version || '1.0.0',
      target: parsed.target,
      layer: parsed.layer,
      tags: parsed.tags || [],
      short: parsed.short
    };
  }

  /**
   * Parse all scenarios from test spec content
   */
  private parseScenarios(content: string): TestScenario[] {
    const scenarios: TestScenario[] = [];

    // Match scenario blocks
    // Format:
    // ## Scenario: {name}
    // Given: {precondition}
    // When: {action}
    // Then: {expected}

    const scenarioRegex = /##\s+Scenario:\s+(.+?)\n([\s\S]*?)(?=##\s+Scenario:|$)/g;

    let match;
    while ((match = scenarioRegex.exec(content)) !== null) {
      const name = match[1].trim();
      const body = match[2];

      const scenario: TestScenario = {
        name,
        given: this.parseList(body, 'Given'),
        when: this.parseSingle(body, 'When'),
        then: this.parseList(body, 'Then')
      };

      // Check for examples table
      const examples = this.parseExamples(body);
      if (examples) {
        scenario.examples = examples;
      }

      scenarios.push(scenario);
    }

    return scenarios;
  }

  /**
   * Parse a list of items with a given keyword (e.g., Given, Then)
   */
  private parseList(body: string, keyword: string): string[] {
    const items: string[] = [];
    // Match keyword at start of line, capture everything until next keyword or end
    const regex = new RegExp(`^${keyword}:\\s*(.+)$`, 'gm');

    let match;
    while ((match = regex.exec(body)) !== null) {
      items.push(match[1].trim());
    }

    return items;
  }

  /**
   * Parse a single item with a given keyword (e.g., When)
   */
  private parseSingle(body: string, keyword: string): string {
    const regex = new RegExp(`^${keyword}:\\s*(.+)$`, 'm');
    const match = body.match(regex);
    return match ? match[1].trim() : '';
  }

  /**
   * Parse examples table from markdown format
   * | field1 | field2 |
   * |--------|--------|
   * | value1 | value2 |
   */
  private parseExamples(body: string): ExampleTable | null {
    const tableRegex = /\|(.+)\|\n\|[-|\s]+\|\n((?:\|.+\|\n?)+)/;
    const match = body.match(tableRegex);

    if (!match) return null;

    const headers = match[1].split('|').map(h => h.trim()).filter(Boolean);
    const rows = match[2].trim().split('\n').map(row =>
      row.split('|').map(c => c.trim()).filter(Boolean)
    );

    return { headers, rows };
  }
}

/**
 * Parse a test spec from a file
 */
export async function parseTestSpecFile(filepath: string): Promise<TestSpec> {
  const fs = await import('fs/promises');
  const content = await fs.readFile(filepath, 'utf-8');
  const parser = new TestSpecParser();
  return parser.parse(content);
}
