// SPECLANG-GENERATED: This file was generated by the speclang-code-gen agent
// Source: @speclang/test-specs/reporter
// DO NOT EDIT MANUALLY

import { TestReport, TestResult } from './types';

/**
 * TestSpecReporter formats test results for display
 */
export class TestSpecReporter {
  /**
   * Format a single test report as a readable string
   */
  formatReport(report: TestReport): string {
    const lines: string[] = [];

    lines.push(`Test Report: ${report.specId}`);
    lines.push('─'.repeat(40));
    lines.push(`Scenarios: ${report.totalScenarios}`);
    lines.push(`  ✓ Passed: ${report.passed}`);
    lines.push(`  ✗ Failed: ${report.failed}`);
    lines.push(`  ○ Skipped: ${report.skipped}`);
    lines.push(`Duration: ${report.duration}ms`);
    lines.push('');

    for (const result of report.results) {
      const icon = result.status === 'passed' ? '✓' :
                   result.status === 'failed' ? '✗' : '○';
      lines.push(`  ${icon} ${result.scenarioName} (${result.duration}ms)`);

      if (result.error) {
        lines.push(`    Error: ${this.truncateError(result.error)}`);
      }
    }

    return lines.join('\n');
  }

  /**
   * Format multiple test reports as a summary
   */
  formatSummary(reports: TestReport[]): string {
    const totals = reports.reduce((acc, r) => ({
      total: acc.total + r.totalScenarios,
      passed: acc.passed + r.passed,
      failed: acc.failed + r.failed,
      skipped: acc.skipped + r.skipped,
      duration: acc.duration + r.duration
    }), { total: 0, passed: 0, failed: 0, skipped: 0, duration: 0 });

    const passRate = totals.total > 0 
      ? ((totals.passed / totals.total) * 100).toFixed(1) 
      : '0.0';

    return `
Test Summary
═══════════════════════════════════════
Specs: ${reports.length}
Scenarios: ${totals.total}
  ✓ Passed: ${totals.passed}
  ✗ Failed: ${totals.failed}
  ○ Skipped: ${totals.skipped}
Pass Rate: ${passRate}%
Duration: ${totals.duration}ms
`.trim();
  }

  /**
   * Format a test result as JSON
   */
  formatJson(report: TestReport): string {
    return JSON.stringify(report, null, 2);
  }

  /**
   * Format reports as JSON array
   */
  formatJsonAll(reports: TestReport[]): string {
    return JSON.stringify(reports, null, 2);
  }

  /**
   * Format a compact single-line summary
   */
  formatCompact(report: TestReport): string {
    const status = report.failed > 0 ? '✗' : report.skipped > 0 ? '○' : '✓';
    return `${status} ${report.specId}: ${report.passed}/${report.totalScenarios} passed (${report.duration}ms)`;
  }

  /**
   * Format failures only
   */
  formatFailures(reports: TestReport[]): string {
    const lines: string[] = ['Failed Tests', '─'.repeat(40)];

    for (const report of reports) {
      const failures = report.results.filter(r => r.status === 'failed');
      if (failures.length > 0) {
        lines.push(`\n${report.specId}:`);
        for (const failure of failures) {
          lines.push(`  ✗ ${failure.scenarioName}`);
          if (failure.error) {
            lines.push(`    ${this.truncateError(failure.error, 100)}`);
          }
        }
      }
    }

    return lines.join('\n');
  }

  /**
   * Get summary statistics
   */
  getSummaryStats(reports: TestReport[]): {
    totalSpecs: number;
    totalScenarios: number;
    totalPassed: number;
    totalFailed: number;
    totalSkipped: number;
    totalDuration: number;
    passRate: number;
  } {
    const totals = reports.reduce((acc, r) => ({
      specs: acc.specs + 1,
      scenarios: acc.scenarios + r.totalScenarios,
      passed: acc.passed + r.passed,
      failed: acc.failed + r.failed,
      skipped: acc.skipped + r.skipped,
      duration: acc.duration + r.duration
    }), { specs: 0, scenarios: 0, passed: 0, failed: 0, skipped: 0, duration: 0 });

    return {
      totalSpecs: totals.specs,
      totalScenarios: totals.scenarios,
      totalPassed: totals.passed,
      totalFailed: totals.failed,
      totalSkipped: totals.skipped,
      totalDuration: totals.duration,
      passRate: totals.scenarios > 0 
        ? (totals.passed / totals.scenarios) * 100 
        : 0
    };
  }

  /**
   * Truncate error message to a reasonable length
   */
  private truncateError(error: string, maxLength: number = 200): string {
    if (error.length <= maxLength) return error;
    return error.substring(0, maxLength) + '...';
  }
}

/**
 * Create a default reporter instance
 */
export const defaultReporter = new TestSpecReporter();

/**
 * Format a test report using default reporter
 */
export function formatReport(report: TestReport): string {
  return defaultReporter.formatReport(report);
}

/**
 * Format test summary using default reporter
 */
export function formatSummary(reports: TestReport[]): string {
  return defaultReporter.formatSummary(reports);
}
