// SPECLANG-GENERATED: This file was generated by the speclang-code-gen agent
// Source: @speclang/test-specs/runner
// DO NOT EDIT MANUALLY

import * as fs from 'fs/promises';
import * as path from 'path';
import { glob } from 'glob';
import { TestSpecParser, parseTestSpecFile } from './parser';
import { TestGenerator } from './generator';
import { TestReport, TestResult, SupportedLanguage } from './types';

/**
 * TestRunner executes test specs and collects results
 */
export class TestRunner {
  private language: SupportedLanguage;

  constructor(language: SupportedLanguage = 'typescript') {
    this.language = language;
  }

  /**
   * Run a single test spec file
   */
  async runTestSpec(specPath: string): Promise<TestReport> {
    const parser = new TestSpecParser();
    const content = await fs.readFile(specPath, 'utf-8');
    const testSpec = parser.parse(content);

    // Generate test file
    const generator = new TestGenerator();
    const testCode = generator.generate(testSpec, this.language);

    // Write to temp file
    const testPath = specPath.replace('.test.spec.md', '.generated.test.ts');
    await fs.writeFile(testPath, testCode);

    // Run tests
    const results = await this.executeTests(testPath);

    return {
      specId: testSpec.id,
      totalScenarios: testSpec.scenarios.length,
      passed: results.filter(r => r.status === 'passed').length,
      failed: results.filter(r => r.status === 'failed').length,
      skipped: results.filter(r => r.status === 'skipped').length,
      duration: results.reduce((sum, r) => sum + r.duration, 0),
      results
    };
  }

  /**
   * Execute tests and parse results
   */
  private async executeTests(testPath: string): Promise<TestResult[]> {
    const results: TestResult[] = [];

    try {
      // Run bun test and capture JSON output
      const { exec } = await import('child_process');
      const { promisify } = await import('util');
      const execAsync = promisify(exec);

      try {
        const { stdout } = await execAsync(`bun test ${testPath} --reporter=json 2>&1`, {
          timeout: 30000
        });

        // Parse JSON output
        const testOutput = JSON.parse(stdout);

        for (const test of testOutput.tests || []) {
          results.push({
            specId: testPath,
            scenarioName: test.name,
            status: test.status as 'passed' | 'failed' | 'skipped',
            duration: test.duration || 0,
            error: test.error?.message || test.error,
            timestamp: Date.now()
          });
        }
      } catch (execError: any) {
        // If tests fail to run, create a failed result
        results.push({
          specId: testPath,
          scenarioName: 'test execution',
          status: 'failed',
          duration: 0,
          error: execError.message || 'Failed to execute tests',
          timestamp: Date.now()
        });
      }
    } catch (error: any) {
      results.push({
        specId: testPath,
        scenarioName: 'unknown',
        status: 'failed',
        duration: 0,
        error: error.message || 'Unknown error',
        timestamp: Date.now()
      });
    }

    return results;
  }

  /**
   * Run all test specs in a directory
   */
  async runAllTestSpecs(dir: string): Promise<TestReport[]> {
    const files = await this.findTestSpecs(dir);
    const reports: TestReport[] = [];

    for (const file of files) {
      try {
        const report = await this.runTestSpec(file);
        reports.push(report);
      } catch (error: any) {
        // Create a failure report for specs that couldn't run
        reports.push({
          specId: file,
          totalScenarios: 0,
          passed: 0,
          failed: 0,
          skipped: 0,
          duration: 0,
          results: [{
            specId: file,
            scenarioName: 'spec parsing',
            status: 'failed',
            duration: 0,
            error: error.message,
            timestamp: Date.now()
          }]
        });
      }
    }

    return reports;
  }

  /**
   * Find all test spec files in a directory
   */
  private async findTestSpecs(dir: string): Promise<string[]> {
    const pattern = path.join(dir, '**/*.test.spec.md');
    return glob(pattern, { absolute: true });
  }

  /**
   * Generate test code without running
   */
  async generateOnly(specPath: string, outputPath?: string): Promise<string> {
    const parser = new TestSpecParser();
    const content = await fs.readFile(specPath, 'utf-8');
    const testSpec = parser.parse(content);

    const generator = new TestGenerator();
    const testCode = generator.generate(testSpec, this.language);

    if (outputPath) {
      await fs.writeFile(outputPath, testCode);
    }

    return testCode;
  }
}

/**
 * Run a test spec and return results
 */
export async function runTestSpec(
  specPath: string,
  language: SupportedLanguage = 'typescript'
): Promise<TestReport> {
  const runner = new TestRunner(language);
  return runner.runTestSpec(specPath);
}

/**
 * Run all test specs in a directory
 */
export async function runAllTestSpecs(
  dir: string,
  language: SupportedLanguage = 'typescript'
): Promise<TestReport[]> {
  const runner = new TestRunner(language);
  return runner.runAllTestSpecs(dir);
}
