/**
speclang-header lines:5
id: @specs/meta
version: 1.0.0
layer: 5
 */

// SPECLANG-GENERATED
// This file is auto-generated by src/meta/bootstrap.ts
// Source: @speclang/meta-bootstrap

import * as fs from "fs-extra";
import * as path from "path";
import {
  SpecFile,
  BootstrapResult,
  BootstrapPhase,
  SourceSpecMapping,
} from "./types.js";
import { SpecGenerator } from "./generator.js";
import { SelfConsistencyValidator } from "./validator.js";

/**
 * MetaBootstrap - The meta-circular bootstrap process
 * 
 * This implements the self-specifying system that:
 * 1. Generates specs from existing code
 * 2. Validates self-consistency
 * 3. Generates code from specs
 * 4. Verifies equivalence
 * 5. Commits self-specification
 */
export class MetaBootstrap {
  private projectRoot: string;
  private generator: SpecGenerator;
  private validator: SelfConsistencyValidator;
  private phases: Map<string, BootstrapPhase>;

  constructor(projectRoot: string = process.cwd()) {
    this.projectRoot = projectRoot;
    this.generator = new SpecGenerator(projectRoot);
    this.validator = new SelfConsistencyValidator(projectRoot);
    this.phases = new Map();
  }

  /**
   * Run the full bootstrap sequence
   */
  async run(dryRun: boolean = false): Promise<BootstrapResult> {
    const startTime = Date.now();
    const errors: string[] = [];

    try {
      // Phase 1: Generate specs from existing code
      this.startPhase("generate-specs");
      const specs = await this.generateSpecsFromCode();
      this.completePhase("generate-specs");

      if (specs.length === 0 && !dryRun) {
        errors.push("No specs were generated");
      }

      // Phase 2: Validate self-consistency
      this.startPhase("validate");
      const validation = await this.validateSelfConsistency();
      this.completePhase("validate");

      if (!validation.passed) {
        const errorMsg = `Validation failed: ${validation.failed} issues found`;
        errors.push(errorMsg);
        if (!dryRun) {
          this.failPhase("validate", errorMsg);
        }
      }

      // Phase 3: Generate code from new specs (if any)
      this.startPhase("generate-code");
      const generated = await this.generateCodeFromSpecs(specs);
      this.completePhase("generate-code");

      // Phase 4: Verify equivalence
      this.startPhase("verify-equivalence");
      const equivalence = await this.verifyEquivalence();
      this.completePhase("verify-equivalence");

      // Phase 5: Commit self-specification (if not dry run)
      this.startPhase("commit");
      if (!dryRun) {
        await this.commitSelfSpecification();
      }
      this.completePhase("commit");

      return {
        success: errors.length === 0 && validation.passed,
        specsGenerated: specs.length,
        validationPassed: validation.passed,
        codeGenerated: generated,
        equivalenceVerified: equivalence.verified,
        errors,
        duration: Date.now() - startTime,
      };
    } catch (error) {
      const errorMsg = (error as Error).message;
      errors.push(errorMsg);
      
      return {
        success: false,
        specsGenerated: 0,
        validationPassed: false,
        codeGenerated: 0,
        equivalenceVerified: false,
        errors,
        duration: Date.now() - startTime,
      };
    }
  }

  /**
   * Generate specs from existing code for key modules
   */
  async generateSpecsFromCode(): Promise<SpecFile[]> {
    const specs: SpecFile[] = [];
    
    // Source directories to generate specs from
    const sourceDirs = [
      { src: "src/db", spec: "specs/sqlite.spec.md" },
      { src: "src/parser", spec: "specs/headers.spec.md" },
      { src: "src/daemon", spec: "specs/daemon.spec.md" },
      { src: "src/agents", spec: "specs/agent-protocol.spec.md" },
      { src: "src/mcp", spec: "specs/mcp.spec.md" },
      { src: "src/codegen", spec: "specs/compiler.spec.md" },
      { src: "src/pipeline", spec: "specs/pipeline.spec.md" },
      { src: "src/guard", spec: "specs/agent-protocol.dir/ownership.spec.md" },
    ];

    for (const dir of sourceDirs) {
      const srcPath = path.join(this.projectRoot, dir.src);
      const specPath = path.join(this.projectRoot, dir.spec);

      if (!(await fs.pathExists(srcPath))) {
        console.log(`Skipping ${dir.src} - directory not found`);
        continue;
      }

      // Generate spec from directory
      const results = await this.generator.generateFromDirectory(
        srcPath,
        path.dirname(specPath)
      );

      for (const result of results) {
        if (result.success && result.spec) {
          // Write the spec file
          await fs.ensureDir(path.dirname(specPath));
          await fs.writeFile(specPath, result.spec.content, "utf-8");
          specs.push(result.spec);
        }
      }
    }

    return specs;
  }

  /**
   * Validate self-consistency of the system
   */
  async validateSelfConsistency(): Promise<{
    passed: boolean;
    totalSpecs: number;
    failed: number;
    issues: any[];
  }> {
    const report = await this.validator.validateAll();

    return {
      passed: report.failed === 0,
      totalSpecs: report.totalSpecs,
      failed: report.failed,
      issues: report.issues,
    };
  }

  /**
   * Generate code from specs
   */
  async generateCodeFromSpecs(specs: SpecFile[]): Promise<number> {
    // In a full implementation, this would use the codegen system
    // For now, we'll just count the specs that would generate code
    return specs.length;
  }

  /**
   * Verify that generated specs are equivalent to existing ones
   */
  async verifyEquivalence(): Promise<{
    verified: boolean;
    differences: string[];
  }> {
    const differences: string[] = [];

    // Compare existing specs with generated ones
    const projectSpec = await this.generator.generateProjectSpec();

    // Check that we have core specs
    if (projectSpec.core.length === 0) {
      differences.push("No core specs found");
    }

    // Check that we have implementation specs
    if (projectSpec.implementation.length === 0) {
      differences.push("No implementation specs found");
    }

    return {
      verified: differences.length === 0,
      differences,
    };
  }

  /**
   * Commit the self-specification state
   */
  async commitSelfSpecification(): Promise<void> {
    // In a full implementation, this would:
    // 1. Create a git commit with the generated specs
    // 2. Tag the commit as a self-specification checkpoint
    // 3. Update the _index.json
    
    console.log("Self-specification committed (simulated)");
  }

  /**
   * Get status of all bootstrap phases
   */
  getPhaseStatus(): BootstrapPhase[] {
    return Array.from(this.phases.values());
  }

  /**
   * Get mappings between source code and specs
   */
  async getSourceSpecMappings(): Promise<SourceSpecMapping[]> {
    const mappings: SourceSpecMapping[] = [];
    
    const sourceDirs = [
      "src/db",
      "src/parser", 
      "src/daemon",
      "src/agents",
      "src/mcp",
      "src/codegen",
      "src/pipeline",
      "src/guard",
    ];

    for (const srcDir of sourceDirs) {
      const srcPath = path.join(this.projectRoot, srcDir);
      
      if (!(await fs.pathExists(srcPath))) {
        continue;
      }

      const specPath = this.specPathForSourceDir(srcDir);
      
      if (await fs.pathExists(path.join(this.projectRoot, specPath))) {
        mappings.push({
          sourcePath: srcDir,
          specPath,
          blockMappings: [],
        });
      }
    }

    return mappings;
  }

  // ===========================================================================
  // Private Methods
  // ===========================================================================

  private startPhase(name: string): void {
    this.phases.set(name, {
      name,
      status: "running",
    });
  }

  private completePhase(name: string): void {
    const phase = this.phases.get(name);
    if (phase) {
      phase.status = "completed";
      phase.duration = (phase.duration || 0) + 1;
    }
  }

  private failPhase(name: string, error: string): void {
    const phase = this.phases.get(name);
    if (phase) {
      phase.status = "failed";
      phase.error = error;
    }
  }

  private specPathForSourceDir(srcDir: string): string {
    const mapping: Record<string, string> = {
      "src/db": "specs/sqlite.spec.md",
      "src/parser": "specs/headers.spec.md",
      "src/daemon": "specs/daemon.spec.md",
      "src/agents": "specs/agent-protocol.spec.md",
      "src/mcp": "specs/mcp.spec.md",
      "src/codegen": "specs/compiler.spec.md",
      "src/pipeline": "specs/pipeline.spec.md",
      "src/guard": "specs/agent-protocol.dir/ownership.spec.md",
    };

    return mapping[srcDir] || `specs/${srcDir.replace("src/", "")}.spec.md`;
  }
}

export default MetaBootstrap;
