"use strict";
// SPECLANG-GENERATED
// This file is auto-generated by src/meta/generator.ts
// Source: @speclang/spec-generator
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.SpecGenerator = void 0;
const fs = __importStar(require("fs-extra"));
const path = __importStar(require("path"));
/**
 * SpecGenerator - Generate spec files from existing code
 *
 * This is the core component for making SpecLang self-specifying.
 * It can analyze TypeScript, Go, Python, and other code files
 * and generate corresponding spec files.
 */
class SpecGenerator {
    projectRoot;
    options;
    constructor(projectRoot = process.cwd(), options = {}) {
        this.projectRoot = projectRoot;
        this.options = {
            includeContent: true,
            parseBlocks: true,
            resolveReferences: true,
            targetLanguage: "typescript",
            ...options,
        };
    }
    /**
     * Generate a spec file from a TypeScript source file
     */
    async generateFromTypeScript(filepath) {
        try {
            const fullPath = path.isAbsolute(filepath)
                ? filepath
                : path.join(this.projectRoot, filepath);
            if (!(await fs.pathExists(fullPath))) {
                return { success: false, errors: [`File not found: ${fullPath}`] };
            }
            const content = await fs.readFile(fullPath, "utf-8");
            const spec = this.typescriptToSpec(filepath, content);
            return { success: true, spec, errors: [] };
        }
        catch (error) {
            return { success: false, errors: [error.message] };
        }
    }
    /**
     * Generate a spec file from a Go source file
     */
    async generateFromGo(filepath) {
        try {
            const fullPath = path.isAbsolute(filepath)
                ? filepath
                : path.join(this.projectRoot, filepath);
            if (!(await fs.pathExists(fullPath))) {
                return { success: false, errors: [`File not found: ${fullPath}`] };
            }
            const content = await fs.readFile(fullPath, "utf-8");
            const spec = this.goToSpec(filepath, content);
            return { success: true, spec, errors: [] };
        }
        catch (error) {
            return { success: false, errors: [error.message] };
        }
    }
    /**
     * Generate a spec file from a Python source file
     */
    async generateFromPython(filepath) {
        try {
            const fullPath = path.isAbsolute(filepath)
                ? filepath
                : path.join(this.projectRoot, filepath);
            if (!(await fs.pathExists(fullPath))) {
                return { success: false, errors: [`File not found: ${fullPath}`] };
            }
            const content = await fs.readFile(fullPath, "utf-8");
            const spec = this.pythonToSpec(filepath, content);
            return { success: true, spec, errors: [] };
        }
        catch (error) {
            return { success: false, errors: [error.message] };
        }
    }
    /**
     * Generate project-level spec containing all specs
     */
    async generateProjectSpec() {
        const specsDir = path.join(this.projectRoot, "specs");
        const northstar = await this.findNorthstar(specsDir);
        const core = await this.findSpecsByLayer(specsDir, 0);
        const components = await this.findSpecsByLayer(specsDir, 1, 5);
        const generated = await this.findGeneratedSpecs(specsDir);
        const implementation = await this.findImplementationSpecs(specsDir);
        return {
            northstar,
            core,
            components,
            generated,
            implementation,
        };
    }
    /**
     * Update an existing spec from code changes
     */
    async updateSpecFromCode(specPath, codePath) {
        try {
            const fullSpecPath = path.isAbsolute(specPath)
                ? specPath
                : path.join(this.projectRoot, specPath);
            const fullCodePath = path.isAbsolute(codePath)
                ? codePath
                : path.join(this.projectRoot, codePath);
            if (!(await fs.pathExists(fullSpecPath))) {
                return { success: false, specPath, changes: [], errors: ["Spec file not found"] };
            }
            if (!(await fs.pathExists(fullCodePath))) {
                return { success: false, specPath, changes: [], errors: ["Code file not found"] };
            }
            const specContent = await fs.readFile(fullSpecPath, "utf-8");
            const codeContent = await fs.readFile(fullCodePath, "utf-8");
            const changes = this.detectChanges(specContent, codeContent, specPath, codePath);
            // Write updated spec if there are changes
            if (changes.length > 0) {
                const updatedSpec = this.applyChanges(specContent, changes);
                await fs.writeFile(fullSpecPath, updatedSpec, "utf-8");
            }
            return { success: true, specPath, changes, errors: [] };
        }
        catch (error) {
            return { success: false, specPath, changes: [], errors: [error.message] };
        }
    }
    /**
     * Generate specs for all source files in a directory
     */
    async generateFromDirectory(dirPath, specOutputDir) {
        const results = [];
        const fullDirPath = path.isAbsolute(dirPath)
            ? dirPath
            : path.join(this.projectRoot, dirPath);
        if (!(await fs.pathExists(fullDirPath))) {
            return [{ success: false, errors: [`Directory not found: ${fullDirPath}`] }];
        }
        const files = await this.getSourceFiles(fullDirPath);
        await fs.ensureDir(path.join(this.projectRoot, specOutputDir));
        for (const file of files) {
            const ext = path.extname(file);
            let result;
            if (ext === ".ts" || ext === ".tsx") {
                result = await this.generateFromTypeScript(file);
            }
            else if (ext === ".go") {
                result = await this.generateFromGo(file);
            }
            else if (ext === ".py") {
                result = await this.generateFromPython(file);
            }
            else {
                continue;
            }
            if (result.success && result.spec) {
                const specPath = this.specPathForCode(file, specOutputDir);
                await fs.writeFile(specPath, result.spec.content, "utf-8");
                result.spec.filePath = specPath;
            }
            results.push(result);
        }
        return results;
    }
    // ===========================================================================
    // Private Methods
    // ===========================================================================
    typescriptToSpec(filepath, content) {
        const header = this.extractFileHeader(filepath, "typescript");
        const blocks = this.extractBlocksFromTypeScript(content);
        const specContent = this.renderSpecFile(header, blocks);
        return {
            header,
            blocks,
            content: specContent,
            filePath: filepath,
        };
    }
    goToSpec(filepath, content) {
        const header = this.extractFileHeader(filepath, "go");
        const blocks = this.extractBlocksFromGo(content);
        const specContent = this.renderSpecFile(header, blocks);
        return {
            header,
            blocks,
            content: specContent,
            filePath: filepath,
        };
    }
    pythonToSpec(filepath, content) {
        const header = this.extractFileHeader(filepath, "python");
        const blocks = this.extractBlocksFromPython(content);
        const specContent = this.renderSpecFile(header, blocks);
        return {
            header,
            blocks,
            content: specContent,
            filePath: filepath,
        };
    }
    extractFileHeader(filepath, lang) {
        const basename = path.basename(filepath, path.extname(filepath));
        const id = `@speclang/${basename.replace(/[-_]/g, "/")}`;
        return {
            id,
            version: "0.1.0",
            layer: 5,
            project_level: "Alpha",
            agent_support: "agent_autonomous",
            tags: [lang, "generated", "auto-generated"],
            short: `Auto-generated spec for ${path.basename(filepath)}`,
            status: "generated",
        };
    }
    extractBlocksFromTypeScript(content) {
        const blocks = [];
        const lines = content.split("\n");
        let currentBlock = null;
        let braceDepth = 0;
        let lineNumber = 0;
        // Class detection
        const classRegex = /^export\s+(class|interface|type|enum)\s+(\w+)/;
        // Function detection  
        const functionRegex = /^export\s+(async\s+)?function\s+(\w+)/;
        // Const detection
        const constRegex = /^export\s+(const|let|var)\s+(\w+)/;
        for (const line of lines) {
            lineNumber++;
            const classMatch = line.match(classRegex);
            const functionMatch = line.match(functionRegex);
            const constMatch = line.match(constRegex);
            if (classMatch || functionMatch || constMatch) {
                const match = classMatch || functionMatch || constMatch;
                const kind = classMatch ? "entity" : "code";
                blocks.push({
                    id: `${match[2].toLowerCase()}`,
                    kind,
                    content: line.trim(),
                    references: this.extractReferences(line),
                    lineStart: lineNumber,
                    lineEnd: lineNumber,
                });
            }
            // Track brace depth for blocks
            braceDepth += (line.match(/{/g) || []).length;
            braceDepth -= (line.match(/}/g) || []).length;
        }
        return blocks;
    }
    extractBlocksFromGo(content) {
        const blocks = [];
        const lines = content.split("\n");
        let lineNumber = 0;
        // Go type detection
        const typeRegex = /^(type|func|var|const)\s+(\w+)/;
        for (const line of lines) {
            lineNumber++;
            const match = line.match(typeRegex);
            if (match) {
                blocks.push({
                    id: `${match[2].toLowerCase()}`,
                    kind: match[1] === "type" ? "entity" : "code",
                    content: line.trim(),
                    references: this.extractReferences(line),
                    lineStart: lineNumber,
                    lineEnd: lineNumber,
                });
            }
        }
        return blocks;
    }
    extractBlocksFromPython(content) {
        const blocks = [];
        const lines = content.split("\n");
        let lineNumber = 0;
        let currentClass = null;
        // Python detection
        const classRegex = /^class\s+(\w+)/;
        const functionRegex = /^(\s*)def\s+(\w+)/;
        const constRegex = /^(\w+)\s*=\s*(?!.*def).*$/;
        for (const line of lines) {
            lineNumber++;
            const classMatch = line.match(classRegex);
            const functionMatch = line.match(functionRegex);
            if (classMatch) {
                currentClass = classMatch[1].toLowerCase();
                blocks.push({
                    id: currentClass,
                    kind: "entity",
                    content: line.trim(),
                    references: this.extractReferences(line),
                    lineStart: lineNumber,
                    lineEnd: lineNumber,
                });
            }
            else if (functionMatch && currentClass) {
                blocks.push({
                    id: `${currentClass}/${functionMatch[2].toLowerCase()}`,
                    kind: "code",
                    content: line.trim(),
                    references: this.extractReferences(line),
                    lineStart: lineNumber,
                    lineEnd: lineNumber,
                });
            }
        }
        return blocks;
    }
    extractReferences(content) {
        const refRegex = /@ref:([\w/.-]+)/g;
        const refs = [];
        let match;
        while ((match = refRegex.exec(content)) !== null) {
            refs.push(match[1]);
        }
        return refs;
    }
    renderSpecFile(header, blocks) {
        const headerYaml = this.renderHeader(header);
        const blocksContent = blocks.map(b => this.renderBlock(b)).join("\n\n");
        return `# speclang-header lines:${headerYaml.split("\n").length + 2}
${headerYaml}
---

${blocksContent}
`;
    }
    renderHeader(header) {
        const lines = [
            `id: "${header.id}"`,
            `version: ${header.version}`,
            `layer: ${header.layer}`,
            `project_level: ${header.project_level}`,
            `agent_support: ${header.agent_support}`,
            `tags: [${header.tags.join(", ")}]`,
            `short: "${header.short}"`,
        ];
        if (header.status) {
            lines.push(`status: ${header.status}`);
        }
        return lines.join("\n");
    }
    renderBlock(block) {
        const refs = block.references.length > 0
            ? `\n\nrefs:\n${block.references.map(r => `  - @ref:${r}`).join("\n")}`
            : "";
        return `## @block:${block.id} @kind:${block.kind}
\`\`\`${block.kind === "code" ? "typescript" : "text"}
${block.content}
\`\`\`${refs}
`;
    }
    async findNorthstar(dirPath) {
        const northstarPaths = [
            path.join(dirPath, "project.scl"),
            path.join(dirPath, "northstar.scl"),
        ];
        for (const p of northstarPaths) {
            if (await fs.pathExists(p)) {
                const content = await fs.readFile(p, "utf-8");
                return this.parseSpecFile(p, content);
            }
        }
        return null;
    }
    async findSpecsByLayer(dirPath, min, max) {
        const specs = [];
        const files = await fs.readdir(dirPath, { withFileTypes: true });
        for (const file of files) {
            if (file.isFile() && (file.name.endsWith(".spec.md") || file.name.endsWith(".scl"))) {
                const fullPath = path.join(dirPath, file.name);
                const content = await fs.readFile(fullPath, "utf-8");
                const spec = this.parseSpecFile(fullPath, content);
                if (max !== undefined) {
                    if (spec.header.layer >= min && spec.header.layer <= max) {
                        specs.push(spec);
                    }
                }
                else if (spec.header.layer === min) {
                    specs.push(spec);
                }
            }
        }
        return specs;
    }
    async findGeneratedSpecs(dirPath) {
        const generatedDir = path.join(dirPath, "generated");
        if (!(await fs.pathExists(generatedDir))) {
            return [];
        }
        return this.findSpecsByLayer(generatedDir, 0);
    }
    async findImplementationSpecs(dirPath) {
        const implDir = path.join(dirPath, "implementation.spec.dir");
        if (!(await fs.pathExists(implDir))) {
            return [];
        }
        const specs = [];
        const files = await fs.readdir(implDir, { withFileTypes: true });
        for (const file of files) {
            if (file.isFile() && file.name.endsWith(".spec.md")) {
                const fullPath = path.join(implDir, file.name);
                const content = await fs.readFile(fullPath, "utf-8");
                specs.push(this.parseSpecFile(fullPath, content));
            }
        }
        return specs;
    }
    parseSpecFile(filepath, content) {
        const header = this.parseHeader(content);
        const blocks = this.parseBlocks(content);
        return {
            header,
            blocks,
            content,
            filePath: filepath,
        };
    }
    parseHeader(content) {
        const headerMatch = content.match(/^# speclang-header lines:(\d+)\n([\s\S]*?)^---/m);
        if (!headerMatch) {
            return {
                id: "@unknown",
                version: "0.0.0",
                layer: 0,
                project_level: "POC",
                agent_support: "human_only",
                tags: [],
                short: "Unknown spec",
            };
        }
        const yamlContent = headerMatch[2];
        const lines = {};
        for (const line of yamlContent.split("\n")) {
            const colonIndex = line.indexOf(":");
            if (colonIndex > 0) {
                const key = line.slice(0, colonIndex).trim();
                const value = line.slice(colonIndex + 1).trim().replace(/^["']|["']$/g, "");
                lines[key] = value;
            }
        }
        return {
            id: lines["id"] || "@unknown",
            version: lines["version"] || "0.0.0",
            layer: parseInt(lines["layer"] || "0", 10),
            project_level: lines["project_level"] || "POC",
            agent_support: lines["agent_support"] || "human_only",
            tags: lines["tags"] ? lines["tags"].replace(/[\[\]]/g, "").split(",").map(t => t.trim()) : [],
            short: lines["short"] || "",
            status: lines["status"],
        };
    }
    parseBlocks(content) {
        const blocks = [];
        const blockRegex = /## @block:(\S+)\s+@kind:(\S+)\n([\s\S]*?)(?=\n## @block:|$)/g;
        let match;
        while ((match = blockRegex.exec(content)) !== null) {
            blocks.push({
                id: match[1],
                kind: match[2],
                content: match[3].trim(),
                references: this.extractReferences(match[3]),
                lineStart: 0,
                lineEnd: 0,
            });
        }
        return blocks;
    }
    detectChanges(specContent, codeContent, specPath, codePath) {
        const changes = [];
        // Simple change detection: compare imports and exports
        const specImports = specContent.match(/@ref:[\w/.-]+/g) || [];
        const codeImports = codeContent.match(/import\s+.*from\s+['"](.*)['"]/g) || [];
        // Check for new exports in code that aren't in spec
        const codeExports = codeContent.match(/export\s+(class|function|const|interface|type)\s+(\w+)/g) || [];
        for (const exp of codeExports) {
            const name = exp.replace(/export\s+(class|function|const|interface|type)\s+/, "");
            if (!specContent.includes(name)) {
                changes.push({
                    type: "added",
                    blockId: name.toLowerCase(),
                    description: `New export found in code: ${name}`,
                });
            }
        }
        return changes;
    }
    applyChanges(specContent, changes) {
        // For now, just append new blocks
        let result = specContent;
        for (const change of changes) {
            if (change.type === "added") {
                const newBlock = `\n## @block:${change.blockId} @kind:code\n\`\`\`typescript\n// Auto-generated from code\n\`\`\`\n`;
                result += newBlock;
            }
        }
        return result;
    }
    async getSourceFiles(dirPath) {
        const files = [];
        const entries = await fs.readdir(dirPath, { withFileTypes: true });
        for (const entry of entries) {
            const fullPath = path.join(dirPath, entry.name);
            if (entry.isDirectory()) {
                const subFiles = await this.getSourceFiles(fullPath);
                files.push(...subFiles);
            }
            else if (/\.(ts|tsx|go|py)$/.test(entry.name)) {
                files.push(fullPath);
            }
        }
        return files;
    }
    specPathForCode(codePath, outputDir) {
        // If codePath is already absolute and outputDir is absolute, use direct path
        if (path.isAbsolute(codePath) && path.isAbsolute(outputDir)) {
            const relativePath = path.relative(path.dirname(outputDir), codePath);
            const basename = path.basename(relativePath, path.extname(relativePath));
            return path.join(outputDir, `${basename}.spec.md`);
        }
        const relativePath = path.relative(this.projectRoot, codePath);
        const basename = path.basename(relativePath, path.extname(relativePath));
        const dirName = path.dirname(relativePath);
        return path.join(this.projectRoot, outputDir, dirName, `${basename}.spec.md`);
    }
}
exports.SpecGenerator = SpecGenerator;
exports.default = SpecGenerator;
//# sourceMappingURL=generator.js.map