"use strict";
// SPECLANG-GENERATED
// This file is auto-generated by src/meta/index.ts
// Source: @speclang/meta-module
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.MetaBootstrap = exports.SelfConsistencyValidator = exports.SpecGenerator = void 0;
exports.executeMetaCommand = executeMetaCommand;
exports.runMetaCLI = runMetaCLI;
/**
 * SpecLang Meta-Specifying System
 *
 * This module provides the self-specifying capabilities for SpecLang:
 * - SpecGenerator: Generate specs from code
 * - SelfConsistencyValidator: Validate spec-code consistency
 * - MetaBootstrap: Run the bootstrap sequence
 *
 * Usage:
 * ```typescript
 * import { SpecGenerator, SelfConsistencyValidator, MetaBootstrap } from './src/meta';
 *
 * // Generate specs from code
 * const generator = new SpecGenerator();
 * const spec = await generator.generateFromTypeScript('src/db/index.ts');
 *
 * // Validate consistency
 * const validator = new SelfConsistencyValidator();
 * const report = await validator.validateAll();
 *
 * // Run bootstrap
 * const bootstrap = new MetaBootstrap();
 * const result = await bootstrap.run();
 * ```
 */
__exportStar(require("./types.js"), exports);
var generator_js_1 = require("./generator.js");
Object.defineProperty(exports, "SpecGenerator", { enumerable: true, get: function () { return generator_js_1.SpecGenerator; } });
var validator_js_1 = require("./validator.js");
Object.defineProperty(exports, "SelfConsistencyValidator", { enumerable: true, get: function () { return validator_js_1.SelfConsistencyValidator; } });
var bootstrap_js_1 = require("./bootstrap.js");
Object.defineProperty(exports, "MetaBootstrap", { enumerable: true, get: function () { return bootstrap_js_1.MetaBootstrap; } });
const validator_js_2 = require("./validator.js");
const bootstrap_js_2 = require("./bootstrap.js");
/**
 * Execute a meta command
 */
async function executeMetaCommand(command, options = {}) {
    const projectRoot = process.cwd();
    switch (command) {
        case "generate": {
            const bootstrap = new bootstrap_js_2.MetaBootstrap(projectRoot);
            const specs = await bootstrap.generateSpecsFromCode();
            return { success: true, specsGenerated: specs.length };
        }
        case "validate": {
            const validator = new validator_js_2.SelfConsistencyValidator(projectRoot);
            const report = await validator.validateAll();
            return {
                success: report.failed === 0,
                totalSpecs: report.totalSpecs,
                passed: report.passed,
                failed: report.failed,
                issues: report.issues,
            };
        }
        case "bootstrap": {
            const bootstrap = new bootstrap_js_2.MetaBootstrap(projectRoot);
            const result = await bootstrap.run(options.dryRun);
            return result;
        }
        case "check": {
            const validator = new validator_js_2.SelfConsistencyValidator(projectRoot);
            const result = await validator.checkSelfSpecifying();
            return result;
        }
        default:
            return { success: false, error: `Unknown command: ${command}` };
    }
}
/**
 * CLI entry point for meta commands
 */
async function runMetaCLI(args) {
    const [command, ...rest] = args;
    const options = {
        dryRun: rest.includes("--dry-run"),
        verbose: rest.includes("--verbose"),
        force: rest.includes("--force"),
    };
    const commandMap = {
        generate: "generate",
        validate: "validate",
        bootstrap: "bootstrap",
        check: "check",
    };
    const metaCommand = commandMap[command];
    if (!metaCommand) {
        console.error(`Unknown meta command: ${command}`);
        console.error(`Available commands: generate, validate, bootstrap, check`);
        process.exit(1);
    }
    try {
        const result = await executeMetaCommand(metaCommand, options);
        console.log(JSON.stringify(result, null, 2));
    }
    catch (error) {
        console.error(`Error: ${error.message}`);
        process.exit(1);
    }
}
//# sourceMappingURL=index.js.map