/**
speclang-header lines:5
id: @specs/meta
version: 1.0.0
layer: 5
 */

// SPECLANG-GENERATED
// This file is auto-generated by src/meta/index.ts
// Source: @speclang/meta-module

/**
 * SpecLang Meta-Specifying System
 * 
 * This module provides the self-specifying capabilities for SpecLang:
 * - SpecGenerator: Generate specs from code
 * - SelfConsistencyValidator: Validate spec-code consistency
 * - MetaBootstrap: Run the bootstrap sequence
 * 
 * Usage:
 * ```typescript
 * import { SpecGenerator, SelfConsistencyValidator, MetaBootstrap } from './src/meta';
 * 
 * // Generate specs from code
 * const generator = new SpecGenerator();
 * const spec = await generator.generateFromTypeScript('src/db/index.ts');
 * 
 * // Validate consistency
 * const validator = new SelfConsistencyValidator();
 * const report = await validator.validateAll();
 * 
 * // Run bootstrap
 * const bootstrap = new MetaBootstrap();
 * const result = await bootstrap.run();
 * ```
 */

export * from "./types.js";
export { SpecGenerator } from "./generator.js";
export { SelfConsistencyValidator } from "./validator.js";
export { MetaBootstrap } from "./bootstrap.js";

// CLI helpers
import { SpecGenerator } from "./generator.js";
import { SelfConsistencyValidator } from "./validator.js";
import { MetaBootstrap } from "./bootstrap.js";
import { MetaCLIOptions, MetaCommand } from "./types.js";

/**
 * Execute a meta command
 */
export async function executeMetaCommand(
  command: MetaCommand,
  options: MetaCLIOptions = {}
): Promise<any> {
  const projectRoot = process.cwd();
  
  switch (command) {
    case "generate": {
      const bootstrap = new MetaBootstrap(projectRoot);
      const specs = await bootstrap.generateSpecsFromCode();
      return { success: true, specsGenerated: specs.length };
    }
    
    case "validate": {
      const validator = new SelfConsistencyValidator(projectRoot);
      const report = await validator.validateAll();
      return {
        success: report.failed === 0,
        totalSpecs: report.totalSpecs,
        passed: report.passed,
        failed: report.failed,
        issues: report.issues,
      };
    }
    
    case "bootstrap": {
      const bootstrap = new MetaBootstrap(projectRoot);
      const result = await bootstrap.run(options.dryRun);
      return result;
    }
    
    case "check": {
      const validator = new SelfConsistencyValidator(projectRoot);
      const result = await validator.checkSelfSpecifying();
      return result;
    }
    
    default:
      return { success: false, error: `Unknown command: ${command}` };
  }
}

/**
 * CLI entry point for meta commands
 */
export async function runMetaCLI(args: string[]): Promise<void> {
  const [command, ...rest] = args;
  
  const options: MetaCLIOptions = {
    dryRun: rest.includes("--dry-run"),
    verbose: rest.includes("--verbose"),
    force: rest.includes("--force"),
  };
  
  const commandMap: Record<string, MetaCommand> = {
    generate: "generate",
    validate: "validate",
    bootstrap: "bootstrap",
    check: "check",
  };
  
  const metaCommand = commandMap[command];
  
  if (!metaCommand) {
    console.error(`Unknown meta command: ${command}`);
    console.error(`Available commands: generate, validate, bootstrap, check`);
    process.exit(1);
  }
  
  try {
    const result = await executeMetaCommand(metaCommand, options);
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error(`Error: ${(error as Error).message}`);
    process.exit(1);
  }
}
