/**
speclang-header lines:5
id: @specs/meta
version: 1.0.0
layer: 5
 */

// SPECLANG-GENERATED
// This file is auto-generated by src/meta/generator.ts
// Source: @speclang/meta-types

/**
 * TypeScript types for the self-specifying system
 * These types define the structure for spec generation and validation
 */

// ============================================================================
// Core Types
// ============================================================================

/** Metadata from spec header */
export interface SpecMetadata {
  id: string;
  version: string;
  layer: number;
  project_level: ProjectLevel;
  agent_support: AgentSupport;
  tags: string[];
  short: string;
  status?: string;
  children?: string[];
  depends_on?: string[];
  parent?: string;
}

export type ProjectLevel =
  | "POC"
  | "MVP"
  | "Alpha"
  | "Beta"
  | "Production"
  | "Startup"
  | "SMB"
  | "MSB"
  | "Enterprise";

export type AgentSupport =
  | "human_only"
  | "agent_assisted"
  | "agent_autonomous";

/** A block within a spec file */
export interface Block {
  id: string;
  kind: BlockKind;
  content: string;
  references: string[];
  lineStart: number;
  lineEnd: number;
}

export type BlockKind =
  | "code"
  | "entity"
  | "diagram"
  | "note"
  | "decision"
  | "table";

/** Complete spec file representation */
export interface SpecFile {
  header: SpecMetadata;
  blocks: Block[];
  content: string;
  filePath: string;
}

/** Project-level spec containing multiple specs */
export interface ProjectSpec {
  northstar: SpecFile | null;
  core: SpecFile[];
  components: SpecFile[];
  generated: SpecFile[];
  implementation: SpecFile[];
}

// ============================================================================
// Generator Types
// ============================================================================

/** Options for spec generation */
export interface GenerateOptions {
  includeContent?: boolean;
  parseBlocks?: boolean;
  resolveReferences?: boolean;
  targetLanguage?: "typescript" | "go" | "python" | "rust";
}

/** Result of generating a spec from code */
export interface GenerateResult {
  success: boolean;
  spec?: SpecFile;
  errors: string[];
}

/** Result of updating a spec from code */
export interface UpdateResult {
  success: boolean;
  specPath: string;
  changes: SpecChange[];
  errors: string[];
}

export interface SpecChange {
  type: "added" | "modified" | "removed";
  blockId: string;
  description: string;
}

// ============================================================================
// Validator Types
// ============================================================================

/** Result of consistency check */
export interface ConsistencyCheck {
  spec: string;
  code: string;
  issues: ConsistencyIssue[];
  passed: boolean;
}

/** A single consistency issue */
export interface ConsistencyIssue {
  type: ConsistencyIssueType;
  specLocation: string;
  codeLocation: string;
  message: string;
  severity: "error" | "warning" | "info";
}

export type ConsistencyIssueType =
  | "missing_block"
  | "extra_block"
  | "type_mismatch"
  | "ref_mismatch"
  | "header_mismatch"
  | "content_changed";

/** Report of all consistency validations */
export interface ConsistencyReport {
  totalSpecs: number;
  passed: number;
  failed: number;
  issues: ConsistencyIssue[];
  timestamp: Date;
  checks: ConsistencyCheck[];
}

/** Result of fixing inconsistencies */
export interface FixReport {
  success: boolean;
  fixed: number;
  failed: number;
  details: FixDetail[];
}

export interface FixDetail {
  issue: ConsistencyIssue;
  action: string;
  success: boolean;
  error?: string;
}

// ============================================================================
// Bootstrap Types
// ============================================================================

/** Result of bootstrap operation */
export interface BootstrapResult {
  success: boolean;
  specsGenerated: number;
  validationPassed: boolean;
  codeGenerated: number;
  equivalenceVerified: boolean;
  errors: string[];
  duration: number;
}

/** Phase status during bootstrap */
export interface BootstrapPhase {
  name: string;
  status: "pending" | "running" | "completed" | "failed";
  duration?: number;
  error?: string;
}

/** Mapping of source code to spec */
export interface SourceSpecMapping {
  sourcePath: string;
  specPath: string;
  blockMappings: BlockMapping[];
}

export interface BlockMapping {
  blockId: string;
  sourceStart: number;
  sourceEnd: number;
  specStart: number;
  specEnd: number;
}

// ============================================================================
// CLI Types
// ============================================================================

/** CLI command options */
export interface MetaCLIOptions {
  dryRun?: boolean;
  verbose?: boolean;
  force?: boolean;
  output?: string;
}

export type MetaCommand = "generate" | "validate" | "bootstrap" | "check";
