"use strict";
// SPECLANG-GENERATED
// This file is auto-generated by src/meta/generator.ts
// Source: @speclang/meta-types
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=types.js.map