// SPECLANG-GENERATED
// This file is auto-generated by src/meta/validator.ts
// Source: @speclang/self-validator

import * as fs from "fs-extra";
import * as path from "path";
import {
  ConsistencyCheck,
  ConsistencyIssue,
  ConsistencyIssueType,
  ConsistencyReport,
  FixReport,
  FixDetail,
} from "./types.js";

/**
export class SelfConsistencyValidator {
  private projectRoot: string;
  private strictMode: boolean;

  constructor(projectRoot: string = process.cwd(), strictMode: boolean = true) {
    this.projectRoot = projectRoot;
    this.strictMode = strictMode;
  }

  /**
   * Validate all specs in the project
   */
  async validateAll(): Promise<ConsistencyReport> {
    const specsDir = path.join(this.projectRoot, "specs");
    const checks: ConsistencyCheck[] = [];
    const allIssues: ConsistencyIssue[] = [];

    if (!(await fs.pathExists(specsDir))) {
      return {
        totalSpecs: 0,
        passed: 0,
        failed: 0,
        issues: [],
        timestamp: new Date(),
        checks: [],
      };
    }

    // Find all spec files
    const specFiles = await this.findSpecFiles(specsDir);
    
    for (const specFile of specFiles) {
      const check = await this.validateSpec(specFile);
      checks.push(check);
      allIssues.push(...check.issues);
    }

    const passed = checks.filter(c => c.passed).length;
    const failed = checks.filter(c => !c.passed).length;

    return {
      totalSpecs: specFiles.length,
      passed,
      failed,
      issues: allIssues,
      timestamp: new Date(),
      checks,
    };
  }

  /**
   * Validate a specific spec file
   */
  async validateSpec(specPath: string): Promise<ConsistencyCheck> {
    const fullPath = path.isAbsolute(specPath)
      ? specPath
      : path.join(this.projectRoot, specPath);

    if (!(await fs.pathExists(fullPath))) {
      return {
        spec: specPath,
        code: "",
        issues: [{
          type: "missing_block",
          specLocation: specPath,
          codeLocation: "",
          message: `Spec file not found: ${specPath}`,
          severity: "error",
        }],
        passed: false,
      };
    }

    const specContent = await fs.readFile(fullPath, "utf-8");
    const issues: ConsistencyIssue[] = [];

    // Parse header
    const headerIssues = this.validateHeader(specContent, specPath);
    issues.push(...headerIssues);

    // Parse blocks and validate references
    const blockIssues = await this.validateBlocks(specContent, specPath);
    issues.push(...blockIssues);

    // Check for corresponding generated code
    const codePath = this.codePathForSpec(specPath);
    if (await fs.pathExists(codePath)) {
      const codeContent = await fs.readFile(codePath, "utf-8");
      const codeIssues = this.validateCodeMatch(specContent, codeContent, specPath, codePath);
      issues.push(...codeIssues);
    }

    return {
      spec: specPath,
      code: codePath,
      issues,
      passed: issues.filter(i => i.severity === "error").length === 0,
    };
  }

  /**
   * Fix inconsistencies automatically where possible
   */
  async fixInconsistencies(): Promise<FixReport> {
    const report = await this.validateAll();
    const details: FixDetail[] = [];

    for (const issue of report.issues) {
      const fixResult = await this.fixIssue(issue);
      details.push(fixResult);
    }

    const fixed = details.filter(d => d.success).length;
    const failed = details.filter(d => !d.success).length;

    return {
      success: failed === 0,
      fixed,
      failed,
      details,
    };
  }

  /**
   * Check if the system is self-specifying
   */
  async checkSelfSpecifying(): Promise<{ isSelfSpecifying: boolean; details: string[] }> {
    const details: string[] = [];
    let isSelfSpecifying = true;

    // Check 1: All source directories have corresponding specs
    const sourceDirs = ["db", "parser", "daemon", "agents", "mcp", "codegen", "pipeline", "guard"];
    
    for (const dir of sourceDirs) {
      const srcPath = path.join(this.projectRoot, "src", dir);
      const specPatterns = [
        path.join(this.projectRoot, "specs", `${dir}.spec.md`),
        path.join(this.projectRoot, "specs", "implementation.spec.dir", `${dir}.spec.md`),
      ];

      const hasSpec = specPatterns.some(p => fs.existsSync(p));
      const hasSrc = await fs.pathExists(srcPath);

      if (hasSrc && !hasSpec) {
        isSelfSpecifying = false;
        details.push(`Missing spec for src/${dir}`);
      } else if (hasSrc && hasSpec) {
        details.push(`✓ src/${dir} has corresponding spec`);
      }
    }

    // Check 2: All generated code has specs
    const generatedDir = path.join(this.projectRoot, "specs", "generated");
    if (await fs.pathExists(generatedDir)) {
      const generatedFiles = await fs.readdir(generatedDir);
      for (const file of generatedFiles) {
        if (file.endsWith(".ts") || file.endsWith(".go")) {
          details.push(`Generated file: ${file}`);
        }
      }
    }

    // Check 3: Validation passes
    const validation = await this.validateAll();
    if (validation.failed > 0) {
      isSelfSpecifying = false;
      details.push(`Validation failed: ${validation.failed} specs have issues`);
    } else {
      details.push("✓ All specs pass validation");
    }

    return { isSelfSpecifying, details };
  }

  // ===========================================================================
  // Private Methods
  // ===========================================================================

  private async findSpecFiles(dirPath: string): Promise<string[]> {
    const files: string[] = [];
    
    if (!(await fs.pathExists(dirPath))) {
      return files;
    }

    const entries = await fs.readdir(dirPath, { withFileTypes: true });
    
    for (const entry of entries) {
      const fullPath = path.join(dirPath, entry.name);
      
      if (entry.isDirectory()) {
        const subFiles = await this.findSpecFiles(fullPath);
        files.push(...subFiles);
      } else if (entry.name.endsWith(".spec.md") || entry.name.endsWith(".scl") || entry.name.endsWith(".spec.yaml")) {
        files.push(fullPath);
      }
    }

    return files;
  }

  private validateHeader(content: string, specPath: string): ConsistencyIssue[] {
    const issues: ConsistencyIssue[] = [];
    
    // Check for header
      issues.push({
        type: "missing_block",
        specLocation: specPath,
        codeLocation: "",
        severity: "error",
      });
      return issues;
    }

    // Validate header fields
    
    if (headerMatch) {
      const yamlContent = headerMatch[2];
      const requiredFields = ["id", "version", "layer", "short"];
      
      for (const field of requiredFields) {
        if (!yamlContent.includes(`${field}:`)) {
          issues.push({
            type: "header_mismatch",
            specLocation: `${specPath}:header`,
            codeLocation: "",
            message: `Missing required header field: ${field}`,
            severity: "warning",
          });
        }
      }
    }

    return issues;
  }

  private async validateBlocks(content: string, specPath: string): Promise<ConsistencyIssue[]> {
    const issues: ConsistencyIssue[] = [];
    
    // Find all block definitions
    const blockRegex = /## @block:(\S+)\s+@kind:(\S+)/g;
    const blocks: { id: string; kind: string }[] = [];
    
    let match;
    while ((match = blockRegex.exec(content)) !== null) {
      blocks.push({ id: match[1], kind: match[2] });
    }

    // Check for duplicate block IDs
    const blockIds = blocks.map(b => b.id);
    const duplicates = blockIds.filter((id, index) => blockIds.indexOf(id) !== index);
    const uniqueDuplicates = Array.from(new Set(duplicates));
    
    for (const dup of uniqueDuplicates) {
      issues.push({
        type: "extra_block",
        specLocation: `${specPath}:${dup}`,
        codeLocation: "",
        message: `Duplicate block ID: ${dup}`,
        severity: "error",
      });
    }

    // Validate block references
    const refRegex = /@ref:([\w/.-]+)/g;
    const refs: string[] = [];
    
    while ((match = refRegex.exec(content)) !== null) {
      refs.push(match[1]);
    }

    // Check if referenced specs exist
    for (const ref of refs) {
      const refPath = this.resolveRefPath(ref, specPath);
      if (!(await fs.pathExists(refPath))) {
        issues.push({
          type: "ref_mismatch",
          specLocation: `${specPath}:refs`,
          codeLocation: refPath,
          message: `Reference points to non-existent spec: ${ref}`,
          severity: this.strictMode ? "error" : "warning",
        });
      }
    }

    return issues;
  }

  private validateCodeMatch(
    specContent: string,
    codeContent: string,
    specPath: string,
    codePath: string
  ): ConsistencyIssue[] {
    const issues: ConsistencyIssue[] = [];
    
    // Extract block IDs from spec
    const blockRegex = /## @block:(\S+)\s+@kind:(\S+)/g;
    const blockIds: string[] = [];
    let match;
    
    while ((match = blockRegex.exec(specContent)) !== null) {
      blockIds.push(match[1]);
    }

    // Extract exports from code
    const exportRegex = /export\s+(class|function|const|interface|type|enum)\s+(\w+)/g;
    const exports: string[] = [];
    
    while ((match = exportRegex.exec(codeContent)) !== null) {
      exports.push(match[2].toLowerCase());
    }

    // Check for missing blocks (in code but not in spec)
    for (const exp of exports) {
      const found = blockIds.some(b => b.toLowerCase().includes(exp));
      if (!found) {
        issues.push({
          type: "missing_block",
          specLocation: specPath,
          codeLocation: codePath,
          message: `Code export "${exp}" has no corresponding spec block`,
          severity: this.strictMode ? "error" : "warning",
        });
      }
    }

    return issues;
  }

  private async fixIssue(issue: ConsistencyIssue): Promise<FixDetail> {
    try {
      switch (issue.type) {
        case "ref_mismatch":
          // Try to create the missing reference or update the ref
          return {
            issue,
            action: "Skipped - requires manual intervention",
            success: false,
          };

        case "missing_block":
          // Could auto-generate blocks, but safer to skip
          return {
            issue,
            action: "Skipped - requires manual review",
            success: false,
          };

        default:
          return {
            issue,
            action: "No auto-fix available",
            success: false,
          };
      }
    } catch (error) {
      return {
        issue,
        action: "Failed",
        success: false,
        error: (error as Error).message,
      };
    }
  }

  private codePathForSpec(specPath: string): string {
    // Try to find corresponding source file
    const relativePath = path.relative(path.join(this.projectRoot, "specs"), specPath);
    const basename = path.basename(relativePath, path.extname(relativePath));
    const dirName = path.dirname(relativePath);
    
    // Check common source locations
    const possiblePaths = [
      path.join(this.projectRoot, "src", dirName, `${basename}.ts`),
      path.join(this.projectRoot, "generated", dirName, `${basename}.ts`),
    ];

    for (const p of possiblePaths) {
      if (fs.existsSync(p)) {
        return p;
      }
    }

    return possiblePaths[0];
  }

  private resolveRefPath(ref: string, fromPath: string): string {
    // Handle different reference formats
    if (ref.startsWith("@ref:")) {
      ref = ref.slice(5);
    }
    
    if (ref.startsWith("@speclang/")) {
      ref = ref.slice(11);
    }

    // Convert to file path
    const refPath = ref.replace(/\//g, ".").replace(/^/, "specs/");
    
    const possibleExtensions = [".spec.md", ".scl", ".spec.yaml", ".spec"];
    
    for (const ext of possibleExtensions) {
      const fullPath = path.join(this.projectRoot, refPath + ext);
      if (fs.existsSync(fullPath)) {
        return fullPath;
      }
    }

    // Check in subdirectories
    const specsDir = path.join(this.projectRoot, "specs");
    return path.join(specsDir, refPath);
  }
}

export default SelfConsistencyValidator;
